#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Generates French department centroids from geo.api.gouv.fr (prefecture proxy).
 *
 * Department codes and labels are read from data/geo_zones/fr.yml (not ps_dictionary).
 *
 * Usage (repo root):
 *   php scripts/geo_zones/generate_fr_centroids.php
 */

$root = dirname(__DIR__, 2);
$autoload = $root . '/src/vendor/autoload.php';
if (!is_file($autoload)) {
  fwrite(STDERR, "Composer autoload not found.\n");
  exit(1);
}
require $autoload;

use Symfony\Component\Yaml\Yaml;

$frYamlPath = $root . '/src/web/modules/custom/ps_search/data/geo_zones/fr.yml';
$outputPath = $root . '/src/web/modules/custom/ps_search/data/geo_zones/centroids/fr.departments.yml';

if (!is_file($frYamlPath)) {
  fwrite(STDERR, "FR geo zones YAML not found: {$frYamlPath}\n");
  exit(1);
}

$payload = Yaml::parse((string) file_get_contents($frYamlPath));
if (!is_array($payload)) {
  fwrite(STDERR, "Invalid YAML: {$frYamlPath}\n");
  exit(1);
}

$codes = [];
foreach (is_array($payload['zones'] ?? NULL) ? $payload['zones'] : [] as $zoneId => $zone) {
  if (!is_array($zone) || ($zone['type'] ?? '') !== 'department') {
    continue;
  }
  $code = strtoupper(trim((string) ($zone['code'] ?? '')));
  if ($code === '') {
    fwrite(STDERR, "Missing department code on zone {$zoneId}\n");
    exit(1);
  }
  $codes[$code] = trim((string) ($zone['label'] ?? ''));
}

if ($codes === []) {
  fwrite(STDERR, "No department zones found in fr.yml.\n");
  exit(1);
}

$centroids = [];
foreach ($codes as $code => $label) {
  $url = sprintf(
    'https://geo.api.gouv.fr/departements/%s/communes?fields=nom,centre,population&format=json&geometry=centre',
    rawurlencode((string) $code),
  );
  $json = @file_get_contents($url);
  if ($json === false) {
    fwrite(STDERR, "Failed to fetch communes for department {$code}\n");
    exit(1);
  }
  $communes = json_decode($json, true);
  if (!is_array($communes) || $communes === []) {
    fwrite(STDERR, "No communes for department {$code}\n");
    exit(1);
  }

  usort($communes, static function (array $a, array $b): int {
    return ((int) ($b['population'] ?? 0)) <=> ((int) ($a['population'] ?? 0));
  });

  $centre = $communes[0]['centre']['coordinates'] ?? NULL;
  if (!is_array($centre) || count($centre) < 2) {
    fwrite(STDERR, "Missing centre for department {$code}\n");
    exit(1);
  }

  $centroids[$code] = [
    'lat' => round((float) $centre[1], 6),
    'lng' => round((float) $centre[0], 6),
    'radius_km' => 45,
  ];
  fwrite(STDOUT, "OK {$code} {$label}\n");
  usleep(100_000);
}

$lines = ["# Generated by scripts/geo_zones/generate_fr_centroids.php — do not edit manually.\n"];
foreach ($centroids as $code => $data) {
  $lines[] = sprintf(
    "%s:\n  lat: %s\n  lng: %s\n  radius_km: %s\n",
    $code,
    $data['lat'],
    $data['lng'],
    $data['radius_km'],
  );
}

$dir = dirname($outputPath);
if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
  fwrite(STDERR, "Unable to create directory: {$dir}\n");
  exit(1);
}

file_put_contents($outputPath, implode("\n", $lines));
fwrite(STDOUT, "Written {$outputPath} (" . count($centroids) . " departments)\n");
