#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Generates French department centroids from geo.api.gouv.fr (prefecture proxy).
 *
 * Usage (repo root):
 *   php scripts/geo_zones/generate_fr_centroids.php
 */

$root = dirname(__DIR__, 2);
$csvPath = $root . '/src/web/modules/custom/ps_dictionary/data/dictionary_entries.csv';
$outputPath = $root . '/src/web/modules/custom/ps_search/data/geo_zones/centroids/fr.departments.yml';

if (!is_file($csvPath)) {
  fwrite(STDERR, "Dictionary CSV not found: {$csvPath}\n");
  exit(1);
}

$codes = [];
$handle = fopen($csvPath, 'rb');
while (($row = fgetcsv($handle)) !== false) {
  if (($row[0] ?? '') !== 'department') {
    continue;
  }
  $code = strtoupper(trim((string) ($row[1] ?? '')));
  if ($code !== '') {
    $codes[$code] = trim((string) ($row[2] ?? ''));
  }
}
fclose($handle);

if ($codes === []) {
  fwrite(STDERR, "No department codes found.\n");
  exit(1);
}

$centroids = [];
foreach ($codes as $code => $label) {
  $url = sprintf(
    'https://geo.api.gouv.fr/departements/%s/communes?fields=nom,centre,population&format=json&geometry=centre',
    rawurlencode((string) $code),
  );
  $json = @file_get_contents($url);
  if ($json === false) {
    fwrite(STDERR, "Failed to fetch communes for department {$code}\n");
    exit(1);
  }
  $communes = json_decode($json, true);
  if (!is_array($communes) || $communes === []) {
    fwrite(STDERR, "No communes for department {$code}\n");
    exit(1);
  }

  usort($communes, static function (array $a, array $b): int {
    return ((int) ($b['population'] ?? 0)) <=> ((int) ($a['population'] ?? 0));
  });

  $centre = $communes[0]['centre']['coordinates'] ?? NULL;
  if (!is_array($centre) || count($centre) < 2) {
    fwrite(STDERR, "Missing centre for department {$code}\n");
    exit(1);
  }

  $centroids[$code] = [
    'lat' => round((float) $centre[1], 6),
    'lng' => round((float) $centre[0], 6),
    'radius_km' => 45,
  ];
  fwrite(STDOUT, "OK {$code} {$label}\n");
  usleep(100_000);
}

$lines = ["# Generated by scripts/geo_zones/generate_fr_centroids.php — do not edit manually.\n"];
foreach ($centroids as $code => $data) {
  $lines[] = sprintf(
    "%s:\n  lat: %s\n  lng: %s\n  radius_km: %s\n",
    $code,
    $data['lat'],
    $data['lng'],
    $data['radius_km'],
  );
}

$dir = dirname($outputPath);
if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
  fwrite(STDERR, "Unable to create directory: {$dir}\n");
  exit(1);
}

file_put_contents($outputPath, implode("\n", $lines));
fwrite(STDOUT, "Written {$outputPath} (" . count($centroids) . " departments)\n");
