<?php

declare(strict_types=1);

/**
 * Contact wizard job title options — aligned with bnppre.fr webforms.
 *
 * @see https://www.bnppre.fr/form/deleguer-recherche
 */

/**
 * Stable CRM option values (submitted values).
 *
 * @return list<string>
 */
function ps_form_contact_job_title_values(): array {
  return array (
  0 => 'Asset manager',
  1 => 'Avocat / Notaire',
  2 => 'CEO / Président',
  3 => 'Chef de projet immobilier',
  4 => 'Chef de projet logistique',
  5 => 'Chef de projet marketing / communication',
  6 => 'Commercial',
  7 => 'Consultant immobilier',
  8 => 'Directeur administratif et financier',
  9 => 'Directeur commercial',
  10 => 'Directeur comptable',
  11 => 'Directeur des achats',
  12 => 'Directeur des investissements et arbitrages',
  13 => 'Directeur des ressources humaines',
  14 => 'Directeur des services généraux',
  15 => 'Directeur immobilier',
  16 => 'Directeur juridique',
  17 => 'Directeur logistique',
  18 => 'Directeur marketing / communication',
  19 => 'Etudiant',
  20 => 'Fund manager',
  21 => 'Gérant / Dirigeant',
  22 => 'Gestionnaire',
  23 => 'Journaliste',
  24 => 'Juriste',
  25 => 'Responsable commercial',
  26 => 'Responsable comptable',
  27 => 'Responsable des achats',
  28 => 'Responsable des services généraux',
  29 => 'Responsable immobilier',
  30 => 'Responsable juridique',
  31 => 'Responsable logistique',
  32 => 'Responsable marketing / communication',
  33 => 'Autre',
);
}

/**
 * @return array<string, array<string, string>>
 */
function ps_form_contact_job_title_strings(): array {
  return array (
  'fr' => 
  array (
    'Asset manager' => 'Asset manager',
    'Avocat / Notaire' => 'Avocat / Notaire',
    'CEO / Président' => 'CEO / Président',
    'Chef de projet immobilier' => 'Chef de projet immobilier',
    'Chef de projet logistique' => 'Chef de projet logistique',
    'Chef de projet marketing / communication' => 'Chef de projet marketing / communication',
    'Commercial' => 'Commercial',
    'Consultant immobilier' => 'Consultant immobilier',
    'Directeur administratif et financier' => 'Directeur administratif et financier',
    'Directeur commercial' => 'Directeur commercial',
    'Directeur comptable' => 'Directeur comptable',
    'Directeur des achats' => 'Directeur des achats',
    'Directeur des investissements et arbitrages' => 'Directeur des investissements et arbitrages',
    'Directeur des ressources humaines' => 'Directeur des ressources humaines',
    'Directeur des services généraux' => 'Directeur des services généraux',
    'Directeur immobilier' => 'Directeur immobilier',
    'Directeur juridique' => 'Directeur juridique',
    'Directeur logistique' => 'Directeur logistique',
    'Directeur marketing / communication' => 'Directeur marketing / communication',
    'Etudiant' => 'Etudiant',
    'Fund manager' => 'Fund manager',
    'Gérant / Dirigeant' => 'Gérant / Dirigeant',
    'Gestionnaire' => 'Gestionnaire',
    'Journaliste' => 'Journaliste',
    'Juriste' => 'Juriste',
    'Responsable commercial' => 'Responsable commercial',
    'Responsable comptable' => 'Responsable comptable',
    'Responsable des achats' => 'Responsable des achats',
    'Responsable des services généraux' => 'Responsable des services généraux',
    'Responsable immobilier' => 'Responsable immobilier',
    'Responsable juridique' => 'Responsable juridique',
    'Responsable logistique' => 'Responsable logistique',
    'Responsable marketing / communication' => 'Responsable marketing / communication',
    'Autre' => 'Autre',
  ),
  'en' => 
  array (
    'Asset manager' => 'Asset manager',
    'Avocat / Notaire' => 'Lawyer / Notary',
    'CEO / Président' => 'CEO / President',
    'Chef de projet immobilier' => 'Real estate project manager',
    'Chef de projet logistique' => 'Logistics project manager',
    'Chef de projet marketing / communication' => 'Marketing / communications project manager',
    'Commercial' => 'Sales',
    'Consultant immobilier' => 'Real estate consultant',
    'Directeur administratif et financier' => 'Chief financial and administrative officer',
    'Directeur commercial' => 'Sales director',
    'Directeur comptable' => 'Chief accountant',
    'Directeur des achats' => 'Head of procurement',
    'Directeur des investissements et arbitrages' => 'Director of investments and asset allocation',
    'Directeur des ressources humaines' => 'HR director',
    'Directeur des services généraux' => 'Head of general services',
    'Directeur immobilier' => 'Real estate director',
    'Directeur juridique' => 'Legal director',
    'Directeur logistique' => 'Logistics director',
    'Directeur marketing / communication' => 'Marketing / communications director',
    'Etudiant' => 'Student',
    'Fund manager' => 'Fund manager',
    'Gérant / Dirigeant' => 'Manager / Executive',
    'Gestionnaire' => 'Portfolio manager',
    'Journaliste' => 'Journalist',
    'Juriste' => 'Legal counsel',
    'Responsable commercial' => 'Sales manager',
    'Responsable comptable' => 'Accounting manager',
    'Responsable des achats' => 'Procurement manager',
    'Responsable des services généraux' => 'General services manager',
    'Responsable immobilier' => 'Real estate manager',
    'Responsable juridique' => 'Legal manager',
    'Responsable logistique' => 'Logistics manager',
    'Responsable marketing / communication' => 'Marketing / communications manager',
    'Autre' => 'Other',
  ),
  'de' => 
  array (
    'Asset manager' => 'Asset Manager',
    'Avocat / Notaire' => 'Anwalt / Notar',
    'CEO / Président' => 'CEO / Präsident',
    'Chef de projet immobilier' => 'Projektleiter Immobilien',
    'Chef de projet logistique' => 'Projektleiter Logistik',
    'Chef de projet marketing / communication' => 'Projektleiter Marketing / Kommunikation',
    'Commercial' => 'Vertrieb',
    'Consultant immobilier' => 'Immobilienberater',
    'Directeur administratif et financier' => 'Finanz- und Verwaltungsdirektor',
    'Directeur commercial' => 'Vertriebsdirektor',
    'Directeur comptable' => 'Buchhaltungsdirektor',
    'Directeur des achats' => 'Einkaufsleiter',
    'Directeur des investissements et arbitrages' => 'Direktor Investitionen und Asset Allocation',
    'Directeur des ressources humaines' => 'Personalchef',
    'Directeur des services généraux' => 'Leiter allgemeine Dienste',
    'Directeur immobilier' => 'Immobiliendirektor',
    'Directeur juridique' => 'Rechtsdirektor',
    'Directeur logistique' => 'Logistikdirektor',
    'Directeur marketing / communication' => 'Marketing- / Kommunikationsdirektor',
    'Etudiant' => 'Student',
    'Fund manager' => 'Fondsmanager',
    'Gérant / Dirigeant' => 'Geschäftsführer / Leiter',
    'Gestionnaire' => 'Manager',
    'Journaliste' => 'Journalist',
    'Juriste' => 'Jurist',
    'Responsable commercial' => 'Vertriebsleiter',
    'Responsable comptable' => 'Buchhaltungsleiter',
    'Responsable des achats' => 'Einkaufsverantwortlicher',
    'Responsable des services généraux' => 'Leiter allgemeine Dienste',
    'Responsable immobilier' => 'Immobilienverantwortlicher',
    'Responsable juridique' => 'Rechtsverantwortlicher',
    'Responsable logistique' => 'Logistikverantwortlicher',
    'Responsable marketing / communication' => 'Marketing- / Kommunikationsverantwortlicher',
    'Autre' => 'Sonstiges',
  ),
  'es' => 
  array (
    'Asset manager' => 'Asset manager',
    'Avocat / Notaire' => 'Abogado / Notario',
    'CEO / Président' => 'CEO / Presidente',
    'Chef de projet immobilier' => 'Jefe de proyecto inmobiliario',
    'Chef de projet logistique' => 'Jefe de proyecto logístico',
    'Chef de projet marketing / communication' => 'Jefe de proyecto marketing / comunicación',
    'Commercial' => 'Comercial',
    'Consultant immobilier' => 'Consultor inmobiliario',
    'Directeur administratif et financier' => 'Director administrativo y financiero',
    'Directeur commercial' => 'Director comercial',
    'Directeur comptable' => 'Director contable',
    'Directeur des achats' => 'Director de compras',
    'Directeur des investissements et arbitrages' => 'Director de inversiones y asignación de activos',
    'Directeur des ressources humaines' => 'Director de recursos humanos',
    'Directeur des services généraux' => 'Director de servicios generales',
    'Directeur immobilier' => 'Director inmobiliario',
    'Directeur juridique' => 'Director jurídico',
    'Directeur logistique' => 'Director logístico',
    'Directeur marketing / communication' => 'Director de marketing / comunicación',
    'Etudiant' => 'Estudiante',
    'Fund manager' => 'Gestor de fondos',
    'Gérant / Dirigeant' => 'Gerente / Directivo',
    'Gestionnaire' => 'Gestor',
    'Journaliste' => 'Periodista',
    'Juriste' => 'Jurista',
    'Responsable commercial' => 'Responsable comercial',
    'Responsable comptable' => 'Responsable contable',
    'Responsable des achats' => 'Responsable de compras',
    'Responsable des services généraux' => 'Responsable de servicios generales',
    'Responsable immobilier' => 'Responsable inmobiliario',
    'Responsable juridique' => 'Responsable jurídico',
    'Responsable logistique' => 'Responsable logístico',
    'Responsable marketing / communication' => 'Responsable de marketing / comunicación',
    'Autre' => 'Otro',
  ),
  'it' => 
  array (
    'Asset manager' => 'Asset manager',
    'Avocat / Notaire' => 'Avvocato / Notaio',
    'CEO / Président' => 'CEO / Presidente',
    'Chef de projet immobilier' => 'Responsabile di progetto immobiliare',
    'Chef de projet logistique' => 'Responsabile di progetto logistico',
    'Chef de projet marketing / communication' => 'Responsabile di progetto marketing / comunicazione',
    'Commercial' => 'Commerciale',
    'Consultant immobilier' => 'Consulente immobiliare',
    'Directeur administratif et financier' => 'Direttore amministrativo e finanziario',
    'Directeur commercial' => 'Direttore commerciale',
    'Directeur comptable' => 'Direttore contabile',
    'Directeur des achats' => 'Direttore acquisti',
    'Directeur des investissements et arbitrages' => 'Direttore investimenti e allocazione degli asset',
    'Directeur des ressources humaines' => 'Direttore risorse umane',
    'Directeur des services généraux' => 'Direttore servizi generali',
    'Directeur immobilier' => 'Direttore immobiliare',
    'Directeur juridique' => 'Direttore legale',
    'Directeur logistique' => 'Direttore logistico',
    'Directeur marketing / communication' => 'Direttore marketing / comunicazione',
    'Etudiant' => 'Studente',
    'Fund manager' => 'Fund manager',
    'Gérant / Dirigeant' => 'Gestore / Dirigente',
    'Gestionnaire' => 'Gestore',
    'Journaliste' => 'Giornalista',
    'Juriste' => 'Legale',
    'Responsable commercial' => 'Responsabile commerciale',
    'Responsable comptable' => 'Responsabile contabile',
    'Responsable des achats' => 'Responsabile acquisti',
    'Responsable des services généraux' => 'Responsabile servizi generali',
    'Responsable immobilier' => 'Responsabile immobiliare',
    'Responsable juridique' => 'Responsabile legale',
    'Responsable logistique' => 'Responsabile logistico',
    'Responsable marketing / communication' => 'Responsabile marketing / comunicazione',
    'Autre' => 'Altro',
  ),
  'nl' => 
  array (
    'Asset manager' => 'Asset manager',
    'Avocat / Notaire' => 'Advocaat / Notaris',
    'CEO / Président' => 'CEO / Voorzitter',
    'Chef de projet immobilier' => 'Projectmanager vastgoed',
    'Chef de projet logistique' => 'Projectmanager logistiek',
    'Chef de projet marketing / communication' => 'Projectmanager marketing / communicatie',
    'Commercial' => 'Commercieel',
    'Consultant immobilier' => 'Vastgoedconsultant',
    'Directeur administratif et financier' => 'Financieel en administratief directeur',
    'Directeur commercial' => 'Commercieel directeur',
    'Directeur comptable' => 'Hoofd boekhouding',
    'Directeur des achats' => 'Inkoopdirecteur',
    'Directeur des investissements et arbitrages' => 'Directeur investeringen en asset allocation',
    'Directeur des ressources humaines' => 'HR-directeur',
    'Directeur des services généraux' => 'Hoofd algemene diensten',
    'Directeur immobilier' => 'Vastgoeddirecteur',
    'Directeur juridique' => 'Juridisch directeur',
    'Directeur logistique' => 'Logistiek directeur',
    'Directeur marketing / communication' => 'Marketing- / communicatiedirecteur',
    'Etudiant' => 'Student',
    'Fund manager' => 'Fondsmanager',
    'Gérant / Dirigeant' => 'Manager / Leidinggevende',
    'Gestionnaire' => 'Beheerder',
    'Journaliste' => 'Journalist',
    'Juriste' => 'Jurist',
    'Responsable commercial' => 'Commercieel verantwoordelijke',
    'Responsable comptable' => 'Boekhoudverantwoordelijke',
    'Responsable des achats' => 'Inkoopverantwoordelijke',
    'Responsable des services généraux' => 'Verantwoordelijke algemene diensten',
    'Responsable immobilier' => 'Vastgoedverantwoordelijke',
    'Responsable juridique' => 'Juridisch verantwoordelijke',
    'Responsable logistique' => 'Logistiek verantwoordelijke',
    'Responsable marketing / communication' => 'Marketing- / communicatieverantwoordelijke',
    'Autre' => 'Anders',
  ),
  'pl' => 
  array (
    'Asset manager' => 'Asset manager',
    'Avocat / Notaire' => 'Prawnik / Notariusz',
    'CEO / Président' => 'CEO / Prezes',
    'Chef de projet immobilier' => 'Kierownik projektu nieruchomości',
    'Chef de projet logistique' => 'Kierownik projektu logistycznego',
    'Chef de projet marketing / communication' => 'Kierownik projektu marketing / komunikacja',
    'Commercial' => 'Handlowiec',
    'Consultant immobilier' => 'Konsultant ds. nieruchomości',
    'Directeur administratif et financier' => 'Dyrektor administracyjno-finansowy',
    'Directeur commercial' => 'Dyrektor handlowy',
    'Directeur comptable' => 'Dyrektor ds. księgowości',
    'Directeur des achats' => 'Dyrektor ds. zakupów',
    'Directeur des investissements et arbitrages' => 'Dyrektor ds. inwestycji i alokacji aktywów',
    'Directeur des ressources humaines' => 'Dyrektor HR',
    'Directeur des services généraux' => 'Dyrektor ds. usług ogólnych',
    'Directeur immobilier' => 'Dyrektor ds. nieruchomości',
    'Directeur juridique' => 'Dyrektor prawny',
    'Directeur logistique' => 'Dyrektor logistyki',
    'Directeur marketing / communication' => 'Dyrektor marketingu / komunikacji',
    'Etudiant' => 'Student',
    'Fund manager' => 'Fund manager',
    'Gérant / Dirigeant' => 'Kierownik / Dyrektor',
    'Gestionnaire' => 'Menedżer',
    'Journaliste' => 'Dziennikarz',
    'Juriste' => 'Prawnik',
    'Responsable commercial' => 'Kierownik ds. sprzedaży',
    'Responsable comptable' => 'Kierownik ds. księgowości',
    'Responsable des achats' => 'Kierownik ds. zakupów',
    'Responsable des services généraux' => 'Kierownik ds. usług ogólnych',
    'Responsable immobilier' => 'Kierownik ds. nieruchomości',
    'Responsable juridique' => 'Kierownik ds. prawnych',
    'Responsable logistique' => 'Kierownik ds. logistyki',
    'Responsable marketing / communication' => 'Kierownik ds. marketingu / komunikacji',
    'Autre' => 'Inne',
  ),
  'lb' => 
  array (
    'Asset manager' => 'Asset manager',
    'Avocat / Notaire' => 'Avocat / Notaire',
    'CEO / Président' => 'CEO / Président',
    'Chef de projet immobilier' => 'Chef de projet immobilier',
    'Chef de projet logistique' => 'Chef de projet logistique',
    'Chef de projet marketing / communication' => 'Chef de projet marketing / communication',
    'Commercial' => 'Commercial',
    'Consultant immobilier' => 'Consultant immobilier',
    'Directeur administratif et financier' => 'Directeur administratif et financier',
    'Directeur commercial' => 'Directeur commercial',
    'Directeur comptable' => 'Directeur comptable',
    'Directeur des achats' => 'Directeur des achats',
    'Directeur des investissements et arbitrages' => 'Directeur des investissements et arbitrages',
    'Directeur des ressources humaines' => 'Directeur des ressources humaines',
    'Directeur des services généraux' => 'Directeur des services généraux',
    'Directeur immobilier' => 'Directeur immobilier',
    'Directeur juridique' => 'Directeur juridique',
    'Directeur logistique' => 'Directeur logistique',
    'Directeur marketing / communication' => 'Directeur marketing / communication',
    'Etudiant' => 'Etudiant',
    'Fund manager' => 'Fund manager',
    'Gérant / Dirigeant' => 'Gérant / Dirigeant',
    'Gestionnaire' => 'Gestionnaire',
    'Journaliste' => 'Journaliste',
    'Juriste' => 'Juriste',
    'Responsable commercial' => 'Responsable commercial',
    'Responsable comptable' => 'Responsable comptable',
    'Responsable des achats' => 'Responsable des achats',
    'Responsable des services généraux' => 'Responsable des services généraux',
    'Responsable immobilier' => 'Responsable immobilier',
    'Responsable juridique' => 'Responsable juridique',
    'Responsable logistique' => 'Responsable logistique',
    'Responsable marketing / communication' => 'Responsable marketing / communication',
    'Autre' => 'Autre',
  ),
);
}

/**
 * YAML-escapes a scalar for webform option keys/labels.
 */
function ps_form_job_title_yq(string $value): string {
  return "'" . str_replace("'", "''", $value) . "'";
}

/**
 * Builds the job_title #options YAML block for a language.
 */
function ps_form_build_contact_job_title_options_yaml(string $lang): string {
  $labels = ps_form_contact_job_title_strings()[$lang]
    ?? ps_form_contact_job_title_strings()['fr'];
  $lines = [];
  foreach (ps_form_contact_job_title_values() as $value) {
    $label = $labels[$value] ?? $value;
    $lines[] = '      ' . ps_form_job_title_yq($value) . ': ' . ps_form_job_title_yq($label);
  }
  return implode("\n", $lines);
}
