enabled_menus:
  - main
disable_assets: true
submenu_icon:
  enabled: 0
  separate_states: 0
  source: unicode
  unicode_expand: ▼
  unicode_collapse: ▲
  font_expand: ''
  font_collapse: ''
  element: span
  aria: 'Toggle submenu'
  aria_expand: Expand
  aria_collapse: Collapse
