import fs from 'fs';
import { glob } from 'glob';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ICONS_SOURCE_DIR = path.join(__dirname, '../source/icons-source');
const SPRITE_OUTPUT_PATH = path.join(__dirname, '../source/assets/icons/icons-sprite.svg');
const CSS_OUTPUT_PATH = path.join(__dirname, '../source/props/icons-generated.css');
const REGISTRY_OUTPUT_PATH = path.join(__dirname, '../source/patterns/documentation/icons-registry.json');

const SVG_SYMBOL_RE = /<svg[^>]*>([\s\S]*?)<\/svg>/i;
const VIEWBOX_RE = /viewBox="([^"]+)"/i;

/**
 * Strip inline fill/stroke from SVG and add fill="currentColor" for CSS color inheritance.
 * This allows icons to inherit color from parent via background-image.
 */
function stripSVGFillStroke(svgContent) {
  // Remove existing fill and stroke attributes
  let cleaned = svgContent
    .replace(/\s*fill="[^"]*"/g, '')
    .replace(/\s*stroke="[^"]*"/g, '')
    .replace(/\s*fill='[^']*'/g, '')
    .replace(/\s*stroke='[^']*'/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  
  // Add fill="currentColor" to all path elements
  cleaned = cleaned.replace(/<path\s/g, '<path fill="currentColor" ');
  
  // Also handle other SVG shape elements (circle, rect, polygon, etc.)
  cleaned = cleaned.replace(/<circle\s/g, '<circle fill="currentColor" ');
  cleaned = cleaned.replace(/<rect\s/g, '<rect fill="currentColor" ');
  cleaned = cleaned.replace(/<polygon\s/g, '<polygon fill="currentColor" ');
  cleaned = cleaned.replace(/<ellipse\s/g, '<ellipse fill="currentColor" ');
  
  return cleaned;
}

/**
 * Generate complete CSS file with all [data-icon="..."] rules
 * Uses mask-image with inline data URIs (SVG fragments don't work with background-image)
 * Input: Array of { name, viewBox, body } objects
 * Output: CSS content string
 */
function generateIconsCss(icons) {
  const cssLines = [
    '/**',
    ' * GENERATED FILE - DO NOT EDIT MANUALLY',
    ' * Generated by: scripts/build-icons.mjs',
    ' * Generated: ' + new Date().toISOString(),
    ' *',
    ' * This file contains all data-icon CSS rules.',
    ' * Icons use mask-image with inline SVG data URIs for currentColor support.',
    ' * To add icons: Drop SVG in source/icons-source/, run: npm run build',
    ' */',
    '',
    '/* Base styling for all data-icon elements */',
    '[data-icon] {',
    '  display: inline-block;',
    '  width: 1em;',
    '  height: 1em;',
    '  font-style: normal;',
    '  font-variant: normal;',
    '  text-transform: none;',
    '  line-height: 1;',
    '  -webkit-font-smoothing: antialiased;',
    '  -moz-osx-font-smoothing: grayscale;',
    '  /* Use mask-image to inherit color via background-color */',
    '  background-color: currentColor;',
    '  mask-repeat: no-repeat;',
    '  mask-position: center;',
    '  mask-size: contain;',
    '  -webkit-mask-repeat: no-repeat;',
    '  -webkit-mask-position: center;',
    '  -webkit-mask-size: contain;',
    '}',
    '',
    `/* Icon mappings (auto-generated - ${icons.length} icons) */`,
  ];

  // Generate one rule per icon with inline SVG data URI
  for (const { name, viewBox, body } of icons.sort((a, b) => a.name.localeCompare(b.name))) {
    // Create complete SVG with viewBox
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body}</svg>`;
    // URL-encode for data URI
    const encoded = svg
      .replace(/%/g, '%25')
      .replace(/</g, '%3C')
      .replace(/>/g, '%3E')
      .replace(/#/g, '%23')
      .replace(/"/g, "'")
      .replace(/\s+/g, ' ')
      .trim();
    
    cssLines.push(
      `[data-icon="${name}"] { mask-image: url("data:image/svg+xml,${encoded}"); -webkit-mask-image: url("data:image/svg+xml,${encoded}"); }`
    );
  }

  return cssLines.join('\n') + '\n';
}

/**
 * Generate icons registry JSON for validation and discovery
 * Categories are based on source folder structure in icons-source/
 * Input: Array of { name, folder } objects
 * Output: JSON object with metadata
 */
function generateIconsRegistry(icons) {
  // Group icons by their source folder
  const categories = {};
  
  for (const { name, folder } of icons) {
    if (!categories[folder]) {
      categories[folder] = [];
    }
    categories[folder].push(name);
  }

  // Sort icons within each category
  for (const folder in categories) {
    categories[folder].sort();
  }

  const iconNames = icons.map(i => i.name).sort();

  const registry = {
    generated: new Date().toISOString(),
    total: iconNames.length,
    names: iconNames,
    categories: categories,
  };

  // Format with proper indentation for biome (2 spaces, max 100 chars line width)
  return JSON.stringify(registry, null, 2);
}

async function buildIcons() {
  const svgFiles = await glob('**/*.svg', {
    cwd: ICONS_SOURCE_DIR,
  });

  if (!svgFiles.length) {
    throw new Error(`No SVG files found in ${ICONS_SOURCE_DIR}`);
  }

  const symbols = [];
  const names = [];
  const icons = []; // Store complete icon data for CSS generation

  for (const file of svgFiles.sort()) {
    const name = path.basename(file, '.svg');
    const folder = path.dirname(file).split(path.sep)[0] || 'root'; // Get first folder level
    const raw = fs.readFileSync(path.join(ICONS_SOURCE_DIR, file), 'utf8');

    const viewBox = VIEWBOX_RE.exec(raw)?.[1] ?? '0 0 24 24';
    const bodyMatch = SVG_SYMBOL_RE.exec(raw);
    let body = bodyMatch ? bodyMatch[1].trim() : raw.trim();

    // Strip inline fill/stroke to allow currentColor
    body = stripSVGFillStroke(body);

    names.push(name);
    symbols.push(`<symbol id="icon-${name}" viewBox="${viewBox}">${body}</symbol>`);
    icons.push({ name, viewBox, body, folder }); // Collect with folder info
  }

  const spriteContent = [
    '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">',
    symbols.join('\n'),
    '</svg>',
    '',
  ].join('\n');

  // Only write if content changed (prevents infinite reload in watch mode)
  let spriteChanged = true;
  let cssChanged = true;
  let registryChanged = true;

  if (fs.existsSync(SPRITE_OUTPUT_PATH)) {
    const existing = fs.readFileSync(SPRITE_OUTPUT_PATH, 'utf8');
    spriteChanged = existing !== spriteContent;
  }

  // Generate and write CSS with icon data
  const cssContent = generateIconsCss(icons);
  if (fs.existsSync(CSS_OUTPUT_PATH)) {
    const existing = fs.readFileSync(CSS_OUTPUT_PATH, 'utf8');
    cssChanged = existing !== cssContent;
  }
  // Generate and write registry with folder-based categories
  const registryContent = generateIconsRegistry(icons);
  if (fs.existsSync(REGISTRY_OUTPUT_PATH)) {
    const existing = fs.readFileSync(REGISTRY_OUTPUT_PATH, 'utf8');
    registryChanged = existing !== registryContent;
  }

  // Write sprite
  if (spriteChanged) {
    fs.mkdirSync(path.dirname(SPRITE_OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(SPRITE_OUTPUT_PATH, spriteContent, 'utf8');
    console.log(`✔ Updated sprite (${symbols.length} symbols) → ${SPRITE_OUTPUT_PATH}`);
  }

  // Write CSS
  if (cssChanged) {
    fs.mkdirSync(path.dirname(CSS_OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(CSS_OUTPUT_PATH, cssContent, 'utf8');
    console.log(`✔ Generated CSS (${names.length} rules) → ${CSS_OUTPUT_PATH}`);
  }

  // Write registry
  if (registryChanged) {
    fs.mkdirSync(path.dirname(REGISTRY_OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(REGISTRY_OUTPUT_PATH, registryContent, 'utf8');
    console.log(`✔ Generated registry (${names.length} icons) → ${REGISTRY_OUTPUT_PATH}`);
  }

  if (!spriteChanged && !cssChanged && !registryChanged) {
    console.log(`✔ No changes detected (${symbols.length} icons)`);
  }
}

const isWatch = process.argv.includes('--watch');

async function run() {
  await buildIcons();

  if (!isWatch) {
    return;
  }

  console.log(`👀 Watching ${ICONS_SOURCE_DIR} for SVG changes...`);

  let timer = null;
  let lastWriteTime = Date.now();
  const debounce = (fn, delay = 150) => {
    clearTimeout(timer);
    timer = setTimeout(fn, delay);
  };

  fs.watch(ICONS_SOURCE_DIR, { recursive: true }, (event, filename) => {
    // Ignore events on non-SVG files
    if (!filename || !filename.endsWith('.svg')) return;

    // Ignore if we just wrote to the files (prevent self-triggering)
    if (Date.now() - lastWriteTime < 500) return;

    debounce(async () => {
      try {
        await buildIcons();
        lastWriteTime = Date.now();
      } catch (error) {
        console.error('Icon build failed during watch:', error);
      }
    });
  });
}

run().catch((error) => {
  console.error('Icon build failed:', error);
  process.exit(1);
});
