import fs from 'fs';
import { glob } from 'glob';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ICONS_SOURCE_DIR = path.join(__dirname, '../source/icons-source');
const SPRITE_OUTPUT_PATH = path.join(__dirname, '../source/assets/icons/icons-sprite.svg');
const CSS_OUTPUT_PATH = path.join(__dirname, '../source/props/icons.css');
const REGISTRY_OUTPUT_PATH = path.join(
  __dirname,
  '../source/patterns/documentation/icons-registry.json'
);

const SVG_SYMBOL_RE = /<svg[^>]*>([\s\S]*?)<\/svg>/i;
const VIEWBOX_RE = /viewBox="([^"]+)"/i;

/**
 * Strip inline fill/stroke from SVG and add fill="currentColor" for CSS color inheritance.
 * This allows icons to inherit color from parent via background-image.
 */
function stripSVGFillStroke(svgContent) {
  // Remove existing fill and stroke attributes
  let cleaned = svgContent
    .replace(/\s*fill="[^"]*"/g, '')
    .replace(/\s*stroke="[^"]*"/g, '')
    .replace(/\s*fill='[^']*'/g, '')
    .replace(/\s*stroke='[^']*'/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  // Add fill="currentColor" to all path elements
  cleaned = cleaned.replace(/<path\s/g, '<path fill="currentColor" ');

  // Also handle other SVG shape elements (circle, rect, polygon, etc.)
  cleaned = cleaned.replace(/<circle\s/g, '<circle fill="currentColor" ');
  cleaned = cleaned.replace(/<rect\s/g, '<rect fill="currentColor" ');
  cleaned = cleaned.replace(/<polygon\s/g, '<polygon fill="currentColor" ');
  cleaned = cleaned.replace(/<ellipse\s/g, '<ellipse fill="currentColor" ');

  return cleaned;
}

/**
 * Generate complete CSS file with [data-icon] pseudo-elements (::before, ::after)
 * Supports data-icon-position attribute: 'start' (::before) or 'end' (::after)
 * Default is 'start' (renders ::before pseudo-element)
 * Uses mask-image with inline data URIs for currentColor support
 * Automatically adds spacing between icon and text content
 * Input: Array of { name, viewBox, body } objects
 * Output: CSS content string
 */
function generateIconsCss(icons) {
  const cssLines = [
    '/**',
    ' * GENERATED FILE - DO NOT EDIT MANUALLY',
    ' * Generated by: scripts/build-icons.mjs',
    ' * Generated: ' + new Date().toISOString(),
    ' *',
    ' * This file contains all [data-icon] pseudo-element (::before, ::after) CSS rules.',
    ' * Icons use mask-image with inline SVG data URIs for currentColor support.',
    ' * Position control: Use data-icon-position="start" (::before, default) or "end" (::after)',
    ' * Spacing: Automatic margin added between icon and text content based on position',
    ' * To add icons: Drop SVG in source/icons-source/, run: npm run build',
    ' */',
    '',
    '/* Base styling for [data-icon] pseudo-elements */',
    '[data-icon] {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: var(--ps-icon-gap, 0.375em);',
    '}',
    '',
    '[data-icon]::before,',
    '[data-icon]::after {',
    '  content: "";',
    '  flex-shrink: 0;',
    '  display: inline-block;',
    '  width: 1em;',
    '  height: 1em;',
    '  font-style: normal;',
    '  font-variant: normal;',
    '  text-transform: none;',
    '  line-height: 1;',
    '  vertical-align: -0.125em;',
    '  -webkit-font-smoothing: antialiased;',
    '  -moz-osx-font-smoothing: grayscale;',
    '  /* Use mask-image to inherit color via background-color */',
    '  background-color: currentColor;',
    '  mask-repeat: no-repeat;',
    '  mask-position: center;',
    '  mask-size: contain;',
    '  -webkit-mask-repeat: no-repeat;',
    '  -webkit-mask-position: center;',
    '  -webkit-mask-size: contain;',
    '}',
    '',
    '/* Default: use ::before for icon (start position) */',
    '[data-icon]::after {',
    '  display: none;',
    '}',
    '',
    '/* When data-icon-position="end", swap: hide ::before, show ::after */',
    '[data-icon-position="end"]::before {',
    '  display: none;',
    '}',
    '',
    '[data-icon-position="end"]::after {',
    '  display: inline-block;',
    '}',
    '',
    '/* Icon-only (no text content): remove gap and flex layout */',
    '[data-icon]:not(:has(::after + *)):not(:has(* + ::before)) {',
    '  display: inline-block;',
    '  gap: 0;',
    '}',
    '',
    '/* Fallback for browsers without :has() - use explicit class or inline-block for icon-only */',
    '[data-icon][data-icon-only] {',
    '  display: inline-block;',
    '  gap: 0;',
    '}',
    '',
    `/* Icon mappings (auto-generated - ${icons.length} icons) */`,
  ];

  // Generate one rule per icon with inline SVG data URI (for both ::before and ::after)
  for (const { name, viewBox, body } of icons.sort((a, b) => a.name.localeCompare(b.name))) {
    // Create complete SVG with viewBox
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body}</svg>`;
    // URL-encode for data URI
    const encoded = svg
      .replace(/%/g, '%25')
      .replace(/</g, '%3C')
      .replace(/>/g, '%3E')
      .replace(/#/g, '%23')
      .replace(/"/g, "'")
      .replace(/\s+/g, ' ')
      .trim();

    cssLines.push(
      `[data-icon="${name}"]::before,`,
      `[data-icon="${name}"]::after { mask-image: url("data:image/svg+xml,${encoded}"); -webkit-mask-image: url("data:image/svg+xml,${encoded}"); }`
    );
  }

  return cssLines.join('\n') + '\n';
}

/**
 * Generate icons registry JSON for validation and discovery
 * Categories are based on source folder structure in icons-source/
 * Input: Array of { name, folder } objects
 * Output: JSON object with metadata (biome-compatible formatting)
 */
function generateIconsRegistry(icons) {
  // Group icons by their source folder
  const categories = {};

  for (const { name, folder } of icons) {
    if (!categories[folder]) {
      categories[folder] = [];
    }
    categories[folder].push(name);
  }

  // Sort icons within each category
  for (const folder in categories) {
    categories[folder].sort();
  }

  const iconNames = icons.map((i) => i.name).sort();

  // Build JSON with biome-compatible formatting:
  // - 2-space indentation
  // - Small arrays (≤3 items) on single line for cleaner formatting
  // - Larger arrays with each element on own line

  const lines = ['{'];
  lines.push('  "generated": "' + new Date().toISOString() + '",');
  lines.push('  "total": ' + iconNames.length + ',');
  lines.push('  "names": [');

  // Each icon name on its own line
  for (let i = 0; i < iconNames.length; i++) {
    const isLast = i === iconNames.length - 1;
    lines.push('    "' + iconNames[i] + '"' + (isLast ? '' : ','));
  }
  lines.push('  ],');
  lines.push('  "categories": {');

  // Format categories: compact small arrays (≤3 items), expand larger ones
  const categoryKeys = Object.keys(categories).sort();
  for (let i = 0; i < categoryKeys.length; i++) {
    const key = categoryKeys[i];
    const items = categories[key];
    const isLastCategory = i === categoryKeys.length - 1;

    // Compact format for small arrays
    if (items.length <= 3) {
      const itemsStr = items.map((item) => `"${item}"`).join(', ');
      lines.push(`    "${key}": [${itemsStr}]${isLastCategory ? '' : ','}`);
    } else {
      // Expanded format for larger arrays
      lines.push(`    "${key}": [`);
      for (let j = 0; j < items.length; j++) {
        const isLastItem = j === items.length - 1;
        lines.push(`      "${items[j]}"${isLastItem ? '' : ','}`);
      }
      lines.push(`    ]${isLastCategory ? '' : ','}`);
    }
  }

  lines.push('  }');
  lines.push('}');

  return lines.join('\n') + '\n';
}

async function buildIcons() {
  const svgFiles = await glob('**/*.svg', {
    cwd: ICONS_SOURCE_DIR,
  });

  if (!svgFiles.length) {
    throw new Error(`No SVG files found in ${ICONS_SOURCE_DIR}`);
  }

  const symbols = [];
  const names = [];
  const icons = []; // Store complete icon data for CSS generation

  for (const file of svgFiles.sort()) {
    const name = path.basename(file, '.svg');
    const folder = path.dirname(file).split(path.sep)[0] || 'root'; // Get first folder level
    const raw = fs.readFileSync(path.join(ICONS_SOURCE_DIR, file), 'utf8');

    const viewBox = VIEWBOX_RE.exec(raw)?.[1] ?? '0 0 24 24';
    const bodyMatch = SVG_SYMBOL_RE.exec(raw);
    let body = bodyMatch ? bodyMatch[1].trim() : raw.trim();

    // Strip inline fill/stroke to allow currentColor
    body = stripSVGFillStroke(body);

    names.push(name);
    symbols.push(`<symbol id="icon-${name}" viewBox="${viewBox}">${body}</symbol>`);
    icons.push({ name, viewBox, body, folder }); // Collect with folder info
  }

  const spriteContent = [
    '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden">',
    symbols.join('\n'),
    '</svg>',
    '',
  ].join('\n');

  // Only write if content changed (prevents infinite reload in watch mode)
  let spriteChanged = true;
  let cssChanged = true;
  let registryChanged = true;

  if (fs.existsSync(SPRITE_OUTPUT_PATH)) {
    const existing = fs.readFileSync(SPRITE_OUTPUT_PATH, 'utf8');
    spriteChanged = existing !== spriteContent;
  }

  // Generate and write CSS with icon data
  const cssContent = generateIconsCss(icons);
  if (fs.existsSync(CSS_OUTPUT_PATH)) {
    const existing = fs.readFileSync(CSS_OUTPUT_PATH, 'utf8');
    cssChanged = existing !== cssContent;
  }
  // Generate and write registry with folder-based categories
  const registryContent = generateIconsRegistry(icons);
  if (fs.existsSync(REGISTRY_OUTPUT_PATH)) {
    const existing = fs.readFileSync(REGISTRY_OUTPUT_PATH, 'utf8');
    registryChanged = existing !== registryContent;
  }

  // Write sprite
  if (spriteChanged) {
    fs.mkdirSync(path.dirname(SPRITE_OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(SPRITE_OUTPUT_PATH, spriteContent, 'utf8');
    console.log(`✔ Updated sprite (${symbols.length} symbols) → ${SPRITE_OUTPUT_PATH}`);
  }

  // Write CSS
  if (cssChanged) {
    fs.mkdirSync(path.dirname(CSS_OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(CSS_OUTPUT_PATH, cssContent, 'utf8');
    console.log(`✔ Generated CSS (${names.length} rules) → ${CSS_OUTPUT_PATH}`);
  }

  // Write registry
  if (registryChanged) {
    fs.mkdirSync(path.dirname(REGISTRY_OUTPUT_PATH), { recursive: true });
    fs.writeFileSync(REGISTRY_OUTPUT_PATH, registryContent, 'utf8');
    console.log(`✔ Generated registry (${names.length} icons) → ${REGISTRY_OUTPUT_PATH}`);
  }

  if (!spriteChanged && !cssChanged && !registryChanged) {
    console.log(`✔ No changes detected (${symbols.length} icons)`);
  }
}

const isWatch = process.argv.includes('--watch');

async function run() {
  await buildIcons();

  if (!isWatch) {
    return;
  }

  console.log(`👀 Watching ${ICONS_SOURCE_DIR} for SVG changes...`);

  let timer = null;
  let lastWriteTime = Date.now();
  const debounce = (fn, delay = 150) => {
    clearTimeout(timer);
    timer = setTimeout(fn, delay);
  };

  fs.watch(ICONS_SOURCE_DIR, { recursive: true }, (event, filename) => {
    // Ignore events on non-SVG files
    if (!filename || !filename.endsWith('.svg')) return;

    // Ignore if we just wrote to the files (prevent self-triggering)
    if (Date.now() - lastWriteTime < 500) return;

    debounce(async () => {
      try {
        await buildIcons();
        lastWriteTime = Date.now();
      } catch (error) {
        console.error('Icon build failed during watch:', error);
      }
    });
  });
}

run().catch((error) => {
  console.error('Icon build failed:', error);
  process.exit(1);
});
