# Generated by build_governance_po_data.py
MANUAL = {
    "- @group (fallback) -": {
        "fr": "- @group (repli) -",
        "de": "- @group (Fallback) -",
        "es": "- @group (reserva) -",
        "it": "- @group (fallback) -",
        "nl": "- @group (fallback) -",
        "pl": "- @group (zapasowa) -",
        "lb": "- @group (Fallback) -"
    },
    "Allow CRM to overwrite display fields": {
        "fr": "Autoriser le CRM à écraser les champs d'affichage",
        "de": "CRM darf Anzeigefelder überschreiben",
        "es": "Permitir que el CRM sobrescriba los campos de visualización",
        "it": "Consenti al CRM di sovrascrivere i campi di visualizzazione",
        "nl": "CRM mag weergavevelden overschrijven",
        "pl": "Zezwól CRM na nadpisywanie pól wyświetlania",
        "lb": "CRM däerf Uweis-Felder iwwerschreiwen"
    },
    "Applies to agent entities during migrate row saves when internal_lock is enabled. Inherit uses the global CRM pipeline default.": {
        "fr": "S'applique aux entités agent lors des sauvegardes migrate si internal_lock est activé. Hériter utilise la valeur par défaut du pipeline CRM global.",
        "de": "Gilt bei Migrate-Zeilenspeicherungen für Agenten-Entitäten, wenn internal_lock aktiviert ist. Erben verwendet die globale CRM-Pipeline-Standardeinstellung.",
        "es": "Se aplica al guardar filas migrate de agentes cuando internal_lock está activado. Heredar usa el valor predeterminado del pipeline CRM global.",
        "it": "Si applica al salvataggio delle righe migrate delle entità agente quando internal_lock è abilitato. Eredita usa l'impostazione predefinita della pipeline CRM globale.",
        "nl": "Van toepassing bij migrate-rijopslag voor agent-entiteiten wanneer internal_lock is ingeschakeld. Overnemen gebruikt de globale CRM-pipelinestandaard.",
        "pl": "Dotyczy zapisu wierszy migrate encji agenta, gdy internal_lock jest włączony. Dziedzicz używa globalnej domyślnej strategii pipeline CRM.",
        "lb": "Gëllt bei Migrate-Zeile fir Agenten-Entitéiten wann internal_lock aktiv ass. Iwwerhuelen benotzt de globalen CRM-Pipeline-Default."
    },
    "Applies to feature groups and definitions during migrate row saves. Inherit uses the global CRM pipeline default.": {
        "fr": "S'applique aux groupes et définitions lors des sauvegardes migrate. Hériter utilise la valeur par défaut du pipeline CRM global.",
        "de": "Gilt für Feature-Gruppen und -Definitionen bei Migrate-Zeilenspeicherungen. Erben verwendet die globale CRM-Pipeline-Standardeinstellung.",
        "es": "Se aplica a grupos y definiciones al guardar filas migrate. Heredar usa el valor predeterminado del pipeline CRM global.",
        "it": "Si applica a gruppi e definizioni durante il salvataggio delle righe migrate. Eredita usa l'impostazione predefinita della pipeline CRM globale.",
        "nl": "Van toepassing op groepen en definities bij migrate-rijopslag. Overnemen gebruikt de globale CRM-pipelinestandaard.",
        "pl": "Dotyczy grup i definicji podczas zapisu wierszy migrate. Dziedzicz używa globalnej domyślnej strategii pipeline CRM.",
        "lb": "Gëllt fir Feature-Gruppen a Definitiounen bei Migrate-Zeile. Iwwerhuelen benotzt de globalen CRM-Pipeline-Default."
    },
    "Applies to media entities during migrate row saves when field_internal_lock is enabled. Inherit uses the global CRM pipeline default.": {
        "fr": "S'applique aux entités média lors des sauvegardes migrate si field_internal_lock est activé. Hériter utilise la valeur par défaut du pipeline CRM global.",
        "de": "Gilt bei Migrate-Zeilenspeicherungen für Medien-Entitäten, wenn field_internal_lock aktiviert ist. Erben verwendet die globale CRM-Pipeline-Standardeinstellung.",
        "es": "Se aplica al guardar filas migrate de medios cuando field_internal_lock está activado. Heredar usa el valor predeterminado del pipeline CRM global.",
        "it": "Si applica al salvataggio delle righe migrate dei media quando field_internal_lock è abilitato. Eredita usa l'impostazione predefinita della pipeline CRM globale.",
        "nl": "Van toepassing bij migrate-rijopslag voor media-entiteiten wanneer field_internal_lock is ingeschakeld. Overnemen gebruikt de globale CRM-pipelinestandaard.",
        "pl": "Dotyczy zapisu wierszy migrate encji mediów, gdy field_internal_lock jest włączony. Dziedzicz używa globalnej domyślnej strategii pipeline CRM.",
        "lb": "Gëllt bei Migrate-Zeile fir Medien-Entitéiten wann field_internal_lock aktiv ass. Iwwerhuelen benotzt de globalen CRM-Pipeline-Default."
    },
    "Applies to offer nodes during migrate row saves when field_internal_lock is enabled. Inherit uses the global CRM pipeline default.": {
        "fr": "S'applique aux nœuds offre lors des sauvegardes migrate si field_internal_lock est activé. Hériter utilise la valeur par défaut du pipeline CRM global.",
        "de": "Gilt bei Migrate-Zeilenspeicherungen für Angebotsknoten, wenn field_internal_lock aktiviert ist. Erben verwendet die globale CRM-Pipeline-Standardeinstellung.",
        "es": "Se aplica al guardar filas migrate de ofertas cuando field_internal_lock está activado. Heredar usa el valor predeterminado del pipeline CRM global.",
        "it": "Si applica al salvataggio delle righe migrate delle offerte quando field_internal_lock è abilitato. Eredita usa l'impostazione predefinita della pipeline CRM globale.",
        "nl": "Van toepassing bij migrate-rijopslag voor aanbiedingsnodes wanneer field_internal_lock is ingeschakeld. Overnemen gebruikt de globale CRM-pipelinestandaard.",
        "pl": "Dotyczy zapisu wierszy migrate węzłów ofert, gdy field_internal_lock jest włączony. Dziedzicz używa globalnej domyślnej strategii pipeline CRM.",
        "lb": "Gëllt bei Migrate-Zeile fir Offer-Noden wann field_internal_lock aktiv ass. Iwwerhuelen benotzt de globalen CRM-Pipeline-Default."
    },
    "Applies when an offer technical element references a feature definition that is not in the catalogue.": {
        "fr": "S'applique lorsqu'un élément technique d'offre référence une définition absente du catalogue.",
        "de": "Gilt, wenn ein technisches Angebotselement eine Feature-Definition referenziert, die nicht im Katalog ist.",
        "es": "Se aplica cuando un elemento técnico de oferta referencia una definición que no está en el catálogo.",
        "it": "Si applica quando un elemento tecnico dell'offerta fa riferimento a una definizione non presente nel catalogo.",
        "nl": "Van toepassing wanneer een technisch offerelement verwijst naar een definitie die niet in de catalogus staat.",
        "pl": "Dotyczy sytuacji, gdy element techniczny oferty odnosi się do definicji nieobecnej w katalogu.",
        "lb": "Gëllt wann en technescht Offer-Element eng Definitioun referenzéiert déi net am Katalog ass."
    },
    "Applies when field_internal_lock is enabled on the media entity.": {
        "fr": "S'applique lorsque field_internal_lock est activé sur l'entité média.",
        "de": "Gilt, wenn field_internal_lock für die Medien-Entität aktiviert ist.",
        "es": "Se aplica cuando field_internal_lock está activado en la entidad de medios.",
        "it": "Si applica quando field_internal_lock è abilitato sull'entità media.",
        "nl": "Van toepassing wanneer field_internal_lock is ingeschakeld op de media-entiteit.",
        "pl": "Dotyczy sytuacji, gdy field_internal_lock jest włączony na encji mediów.",
        "lb": "Gëllt wann field_internal_lock op der Medien-Entitéit aktiv ass."
    },
    "Applies when field_internal_lock is enabled on the offer.": {
        "fr": "S'applique lorsque field_internal_lock est activé sur l'offre.",
        "de": "Gilt, wenn field_internal_lock für das Angebot aktiviert ist.",
        "es": "Se aplica cuando field_internal_lock está activado en la oferta.",
        "it": "Si applica quando field_internal_lock è abilitato sull'offerta.",
        "nl": "Van toepassing wanneer field_internal_lock is ingeschakeld op de aanbieding.",
        "pl": "Dotyczy sytuacji, gdy field_internal_lock jest włączony na ofercie.",
        "lb": "Gëllt wann field_internal_lock op der Offer aktiv ass."
    },
    "Applies when internal_lock is enabled on the agent.": {
        "fr": "S'applique lorsque internal_lock est activé sur l'agent.",
        "de": "Gilt, wenn internal_lock für den Agenten aktiviert ist.",
        "es": "Se aplica cuando internal_lock está activado en el agente.",
        "it": "Si applica quando internal_lock è abilitato sull'agente.",
        "nl": "Van toepassing wanneer internal_lock is ingeschakeld op de agent.",
        "pl": "Dotyczy sytuacji, gdy internal_lock jest włączony na agencie.",
        "lb": "Gëllt wann internal_lock op dem Agent aktiv ass."
    },
    "Back to PS configuration hub": {
        "fr": "Retour au hub de configuration PS",
        "de": "Zurück zum PS-Konfigurationshub",
        "es": "Volver al hub de configuración PS",
        "it": "Torna all'hub di configurazione PS",
        "nl": "Terug naar PS-configuratiehub",
        "pl": "Powrót do centrum konfiguracji PS",
        "lb": "Zréck op de PS-Konfiguratiouns-Hub"
    },
    "CRM import pipeline": {
        "fr": "Pipeline d'import CRM",
        "de": "CRM-Import-Pipeline",
        "es": "Canal de importación CRM",
        "it": "Pipeline di importazione CRM",
        "nl": "CRM-importpipeline",
        "pl": "Potok importu CRM",
        "lb": "CRM-Import-Pipeline"
    },
    "CRM import pipeline settings": {
        "fr": "Paramètres du pipeline d'import CRM",
        "de": "CRM-Import-Pipeline-Einstellungen",
        "es": "Ajustes del canal de importación CRM",
        "it": "Impostazioni pipeline di importazione CRM",
        "nl": "CRM-importpipeline-instellingen",
        "pl": "Ustawienia potoku importu CRM",
        "lb": "CRM-Import-Pipeline-Astellungen"
    },
    "CRM offer import lookups": {
        "fr": "Recherches dictionnaire lors de l'import d'offres CRM",
        "de": "CRM-Angebotsimport-Lookups",
        "es": "Búsquedas de diccionario en importación de ofertas CRM",
        "it": "Lookup dizionario durante import offerte CRM",
        "nl": "Woordenboek-opzoekingen bij CRM-aanbiedingsimport",
        "pl": "Wyszukiwania słownika podczas importu ofert CRM",
        "lb": "CRM-Offer-Import-Lookups"
    },
    "CSV import": {
        "fr": "Import CSV",
        "de": "CSV-Import",
        "es": "Importación CSV",
        "it": "Importazione CSV",
        "nl": "CSV-import",
        "pl": "Import CSV",
        "lb": "CSV-Import"
    },
    "Catalogue-protected definitions": {
        "fr": "Définitions protégées du catalogue",
        "de": "Kataloggeschützte Definitionen",
        "es": "Definiciones protegidas del catálogo",
        "it": "Definizioni protette del catalogo",
        "nl": "Catalogusbeschermde definities",
        "pl": "Definicje chronione katalogiem",
        "lb": "Katalog-geschützt Definitiounen"
    },
    "Catalogue-protected groups are always kept active.": {
        "fr": "Les groupes protégés du catalogue restent toujours actifs.",
        "de": "Kataloggeschützte Gruppen bleiben immer aktiv.",
        "es": "Los grupos protegidos del catálogo siempre permanecen activos.",
        "it": "I gruppi protetti del catalogo restano sempre attivi.",
        "nl": "Catalogusbeschermde groepen blijven altijd actief.",
        "pl": "Grupy chronione katalogiem pozostają zawsze aktywne.",
        "lb": "Katalog-geschützt Gruppen bleiwen ëmmer aktiv."
    },
    "Configuration hierarchy": {
        "fr": "Hiérarchie de configuration",
        "de": "Konfigurationshierarchie",
        "es": "Jerarquía de configuración",
        "it": "Gerarchia di configurazione",
        "nl": "Configuratiehiërarchie",
        "pl": "Hierarchia konfiguracji",
        "lb": "Konfiguratiounshierarchie"
    },
    "Control how CRM/XML imports interact with manually curated agents. Global CRM lock strategy defaults are configured in the @link.": {
        "fr": "Contrôler comment les imports CRM/XML interagissent avec les agents saisis manuellement. Les valeurs par défaut de stratégie de verrouillage CRM globale se configurent dans @link.",
        "de": "Steuern, wie CRM/XML-Importe mit manuell gepflegten Agenten interagieren. Globale CRM-Sperrstrategie-Standards werden in @link konfiguriert.",
        "es": "Controlar cómo las importaciones CRM/XML interactúan con agentes curados manualmente. Los valores predeterminados de estrategia de bloqueo CRM global se configuran en @link.",
        "it": "Controlla come le importazioni CRM/XML interagiscono con agenti curati manualmente. Le impostazioni predefinite della strategia di blocco CRM globale si configurano in @link.",
        "nl": "Bepaal hoe CRM/XML-importen omgaan met handmatig beheerde agenten. Globale CRM-vergrendelingsstandaarden worden geconfigureerd in @link.",
        "pl": "Kontroluj, jak importy CRM/XML współdziałają z ręcznie zarządzanymi agentami. Globalne domyślne strategie blokady CRM konfiguruje się w @link.",
        "lb": "Kontrolléieren, wéi CRM/XML-Importen mat manuell kuratéierte Agenten interagéieren. Global CRM-Spärstrategie-Defaulte ginn an @link konfiguréiert."
    },
    "Control how CRM/XML imports interact with manually curated offer media. Global CRM lock strategy defaults are configured in the @link.": {
        "fr": "Contrôler comment les imports CRM/XML interagissent avec les médias d'offre saisis manuellement. Les valeurs par défaut de stratégie de verrouillage CRM globale se configurent dans @link.",
        "de": "Steuern, wie CRM/XML-Importe mit manuell gepflegten Angebotsmedien interagieren. Globale CRM-Sperrstrategie-Standards werden in @link konfiguriert.",
        "es": "Controlar cómo las importaciones CRM/XML interactúan con medios de oferta curados manualmente. Los valores predeterminados de estrategia de bloqueo CRM global se configuran en @link.",
        "it": "Controlla come le importazioni CRM/XML interagiscono con i media delle offerte curati manualmente. Le impostazioni predefinite della strategia di blocco CRM globale si configurano in @link.",
        "nl": "Bepaal hoe CRM/XML-importen omgaan met handmatig beheerde aanbiedingsmedia. Globale CRM-vergrendelingsstandaarden worden geconfigureerd in @link.",
        "pl": "Kontroluj, jak importy CRM/XML współdziałają z ręcznie zarządzanymi mediami ofert. Globalne domyślne strategie blokady CRM konfiguruje się w @link.",
        "lb": "Kontrolléieren, wéi CRM/XML-Importen mat manuell kuratéierte Offer-Medien interagéieren. Global CRM-Spärstrategie-Defaulte ginn an @link konfiguréiert."
    },
    "Control how CRM/XML imports interact with manually curated offers. Global CRM lock strategy defaults are configured in the @link.": {
        "fr": "Contrôler comment les imports CRM/XML interagissent avec les offres saisies manuellement. Les valeurs par défaut de stratégie de verrouillage CRM globale se configurent dans @link.",
        "de": "Steuern, wie CRM/XML-Importe mit manuell gepflegten Angeboten interagieren. Globale CRM-Sperrstrategie-Standards werden in @link konfiguriert.",
        "es": "Controlar cómo las importaciones CRM/XML interactúan con ofertas curadas manualmente. Los valores predeterminados de estrategia de bloqueo CRM global se configuran en @link.",
        "it": "Controlla come le importazioni CRM/XML interagiscono con offerte curate manualmente. Le impostazioni predefinite della strategia di blocco CRM globale si configurano in @link.",
        "nl": "Bepaal hoe CRM/XML-importen omgaan met handmatig beheerde aanbiedingen. Globale CRM-vergrendelingsstandaarden worden geconfigureerd in @link.",
        "pl": "Kontroluj, jak importy CRM/XML współdziałają z ręcznie zarządzanymi ofertami. Globalne domyślne strategie blokady CRM konfiguruje się w @link.",
        "lb": "Kontrolléieren, wéi CRM/XML-Importen mat manuell kuratéierte Offeren interagéieren. Global CRM-Spärstrategie-Defaulte ginn an @link konfiguréiert."
    },
    "Control how CRM/XML imports interact with the manually curated feature catalogue. Global CRM lock strategy defaults are configured in the @link.": {
        "fr": "Contrôler comment les imports CRM/XML interagissent avec le catalogue de caractéristiques saisi manuellement. Les valeurs par défaut de stratégie de verrouillage CRM globale se configurent dans @link.",
        "de": "Steuern, wie CRM/XML-Importe mit dem manuell gepflegten Feature-Katalog interagieren. Globale CRM-Sperrstrategie-Standards werden in @link konfiguriert.",
        "es": "Controlar cómo las importaciones CRM/XML interactúan con el catálogo de características curado manualmente. Los valores predeterminados de estrategia de bloqueo CRM global se configuran en @link.",
        "it": "Controlla come le importazioni CRM/XML interagiscono con il catalogo caratteristiche curato manualmente. Le impostazioni predefinite della strategia di blocco CRM globale si configurano in @link.",
        "nl": "Bepaal hoe CRM/XML-importen omgaan met de handmatig beheerde kenmerkencatalogus. Globale CRM-vergrendelingsstandaarden worden geconfigureerd in @link.",
        "pl": "Kontroluj, jak importy CRM/XML współdziałają z ręcznie zarządzanym katalogiem cech. Globalne domyślne strategie blokady CRM konfiguruje się w @link.",
        "lb": "Kontrolléieren, wéi CRM/XML-Importen mat dem manuell kuratéierte Feature-Katalog interagéieren. Global CRM-Spärstrategie-Defaulte ginn an @link konfiguréiert."
    },
    "Control how CSV imports and CRM offer migrations interact with manually curated dictionary entries.": {
        "fr": "Contrôler comment les imports CSV et les migrations d'offres CRM interagissent avec les entrées de dictionnaire saisies manuellement.",
        "de": "Steuern, wie CSV-Importe und CRM-Angebotsmigrationen mit manuell gepflegten Wörterbucheinträgen interagieren.",
        "es": "Controlar cómo las importaciones CSV y las migraciones de ofertas CRM interactúan con entradas de diccionario curadas manualmente.",
        "it": "Controlla come le importazioni CSV e le migrazioni offerte CRM interagiscono con voci di dizionario curate manualmente.",
        "nl": "Bepaal hoe CSV-importen en CRM-aanbiedingsmigraties omgaan met handmatig beheerde woordenboekitems.",
        "pl": "Kontroluj, jak importy CSV i migracje ofert CRM współdziałają z ręcznie zarządzanymi wpisami słownika.",
        "lb": "Kontrolléieren, wéi CSV-Importen a CRM-Offer-Migratiounen mat manuell kuratéierte Dictionnaire-Entréeën interagéieren."
    },
    "Create a stub definition from the XML element": {
        "fr": "Créer une définition minimale à partir de l'élément XML",
        "de": "Stub-Definition aus dem XML-Element erstellen",
        "es": "Crear una definición provisional a partir del elemento XML",
        "it": "Crea una definizione stub dall'elemento XML",
        "nl": "Maak een stubdefinitie vanuit het XML-element",
        "pl": "Utwórz definicję zastępczą z elementu XML",
        "lb": "Stub-Definitioun aus dem XML-Element erstellen"
    },
    "Current global lock strategy": {
        "fr": "Stratégie de verrouillage globale actuelle",
        "de": "Aktuelle globale Sperrstrategie",
        "es": "Estrategia de bloqueo global actual",
        "it": "Strategia di blocco globale attuale",
        "nl": "Huidige globale vergrendelingsstrategie",
        "pl": "Bieżąca globalna strategia blokady",
        "lb": "Aktuell global Spärstrategie"
    },
    "Deactivate": {
        "fr": "Désactiver",
        "de": "Deaktivieren",
        "es": "Desactivar",
        "it": "Disattiva",
        "nl": "Deactiveren",
        "pl": "Dezaktywuj",
        "lb": "Deaktivéieren"
    },
    "Default feature group": {
        "fr": "Groupe de caractéristiques par défaut",
        "de": "Standard-Feature-Gruppe",
        "es": "Grupo de características predeterminado",
        "it": "Gruppo caratteristiche predefinito",
        "nl": "Standaard kenmerkengroep",
        "pl": "Domyślna grupa cech",
        "lb": "Standard-Feature-Grupp"
    },
    "Default lock strategy, pipeline folders and upload limits.": {
        "fr": "Stratégie de verrouillage par défaut, dossiers du pipeline et limites de téléversement.",
        "de": "Standard-Sperrstrategie, Pipeline-Ordner und Upload-Limits.",
        "es": "Estrategia de bloqueo predeterminada, carpetas del canal y límites de carga.",
        "it": "Strategia di blocco predefinita, cartelle pipeline e limiti di caricamento.",
        "nl": "Standaard vergrendelingsstrategie, pipeline-mappen en uploadlimieten.",
        "pl": "Domyślna strategia blokady, foldery potoku i limity przesyłania.",
        "lb": "Standard-Spärstrategie, Pipeline-Dossieren an Upload-Limitten."
    },
    "Domain form hints": {
        "fr": "Indications sur les formulaires domaine",
        "de": "Hinweise auf Domänenformularen",
        "es": "Indicaciones en formularios de dominio",
        "it": "Suggerimenti sui moduli di dominio",
        "nl": "Hints op domeinformulieren",
        "pl": "Wskazówki na formularzach domenowych",
        "lb": "Hinweiser op Domain-Formularen"
    },
    "Edit CRM import pipeline settings": {
        "fr": "Modifier les paramètres du pipeline d'import CRM",
        "de": "CRM-Import-Pipeline-Einstellungen bearbeiten",
        "es": "Editar ajustes del canal de importación CRM",
        "it": "Modifica impostazioni pipeline di importazione CRM",
        "nl": "CRM-importpipeline-instellingen bewerken",
        "pl": "Edytuj ustawienia potoku importu CRM",
        "lb": "CRM-Import-Pipeline-Astellungen änneren"
    },
    "Global CRM import defaults apply to all domains unless a domain policy overrides them. Domain forms can show inheritance hints when a setting uses Inherit.": {
        "fr": "Les valeurs CRM globales s'appliquent à tous les domaines sauf override explicite. Les formulaires domaine peuvent afficher des indications d'héritage lorsqu'une option Hériter est sélectionnée.",
        "de": "Globale CRM-Standards gelten für alle Domänen, sofern keine Domänenrichtlinie sie überschreibt. Domänenformulare können Vererbungshinweise anzeigen, wenn eine Einstellung Erben verwendet.",
        "es": "Los valores predeterminados CRM globales se aplican a todos los dominios salvo que una política de dominio los anule. Los formularios de dominio pueden mostrar indicaciones de herencia cuando un ajuste usa Heredar.",
        "it": "Le impostazioni predefinite CRM globali si applicano a tutti i domini salvo override di dominio. I moduli di dominio possono mostrare suggerimenti di eredità quando un'impostazione usa Eredita.",
        "nl": "Globale CRM-standaarden gelden voor alle domeinen tenzij een domeinbeleid ze overschrijft. Domeinformulieren kunnen overerfhint tonen wanneer een instelling Overnemen gebruikt.",
        "pl": "Globalne domyślne ustawienia CRM obowiązują we wszystkich domenach, chyba że polityka domeny je nadpisze. Formularze domenowe mogą pokazywać wskazówki dziedziczenia, gdy ustawienie używa Dziedzicz.",
        "lb": "Global CRM-Defaulte gëllen fir all Domainen ausser eng Domain-Politik iwwerschreift se. Domain-Formulare kënnen Iwwerbleiw-Hinweiser weisen wann eng Astellung Iwwerhuelen benotzt."
    },
    "Global CRM pipeline → domain governance → per-entity protection flags.": {
        "fr": "Pipeline CRM global → gouvernance par domaine → verrous par entité.",
        "de": "Globale CRM-Pipeline → Domänen-Governance → Schutzflags pro Entität.",
        "es": "Canal CRM global → gobernanza de dominio → indicadores de protección por entidad.",
        "it": "Pipeline CRM globale → governance di dominio → flag di protezione per entità.",
        "nl": "Globale CRM-pipeline → domeingovernance → beschermingsvlaggen per entiteit.",
        "pl": "Globalny potok CRM → governance domeny → flagi ochrony encji.",
        "lb": "Global CRM-Pipeline → Domain-Governance → Schutz-Flags pro Entitéit."
    },
    "Import defaults": {
        "fr": "Valeurs par défaut à l'import",
        "de": "Import-Standards",
        "es": "Valores predeterminados de importación",
        "it": "Impostazioni predefinite import",
        "nl": "Importstandaarden",
        "pl": "Domyślne ustawienia importu",
        "lb": "Import-Defaulten"
    },
    "Keep active": {
        "fr": "Garder actif",
        "de": "Aktiv belassen",
        "es": "Mantener activo",
        "it": "Mantieni attivo",
        "nl": "Actief houden",
        "pl": "Pozostaw aktywne",
        "lb": "Aktiv loossen"
    },
    "Keep published": {
        "fr": "Garder publié",
        "de": "Veröffentlicht belassen",
        "es": "Mantener publicado",
        "it": "Mantieni pubblicato",
        "nl": "Gepubliceerd houden",
        "pl": "Pozostaw opublikowane",
        "lb": "Publizéiert loossen"
    },
    "Lock definitions imported from CSV": {
        "fr": "Verrouiller les définitions importées depuis CSV",
        "de": "Aus CSV importierte Definitionen sperren",
        "es": "Bloquear definiciones importadas desde CSV",
        "it": "Blocca definizioni importate da CSV",
        "nl": "Definities geïmporteerd via CSV vergrendelen",
        "pl": "Blokuj definicje importowane z CSV",
        "lb": "Aus CSV importéiert Definitiounen spären"
    },
    "Lock entries imported from CSV": {
        "fr": "Verrouiller les entrées importées depuis CSV",
        "de": "Aus CSV importierte Einträge sperren",
        "es": "Bloquear entradas importadas desde CSV",
        "it": "Blocca voci importate da CSV",
        "nl": "Items geïmporteerd via CSV vergrendelen",
        "pl": "Blokuj wpisy importowane z CSV",
        "lb": "Aus CSV importéiert Entréeën spären"
    },
    "Lock new BO agents by default": {
        "fr": "Verrouiller par défaut les nouveaux agents BO",
        "de": "Neue BO-Agenten standardmäßig sperren",
        "es": "Bloquear por defecto los nuevos agentes BO",
        "it": "Blocca per impostazione predefinita i nuovi agenti BO",
        "nl": "Nieuwe BO-agenten standaard vergrendelen",
        "pl": "Domyślnie blokuj nowych agentów BO",
        "lb": "Nei BO-Agenten standardméisseg spären"
    },
    "Lock new BO definitions by default": {
        "fr": "Verrouiller par défaut les nouvelles définitions BO",
        "de": "Neue BO-Definitionen standardmäßig sperren",
        "es": "Bloquear por defecto las nuevas definiciones BO",
        "it": "Blocca per impostazione predefinita le nuove definizioni BO",
        "nl": "Nieuwe BO-definities standaard vergrendelen",
        "pl": "Domyślnie blokuj nowe definicje BO",
        "lb": "Nei BO-Definitiounen standardméisseg spären"
    },
    "Lock new BO entries by default": {
        "fr": "Verrouiller par défaut les nouvelles entrées BO",
        "de": "Neue BO-Einträge standardmäßig sperren",
        "es": "Bloquear por defecto las nuevas entradas BO",
        "it": "Blocca per impostazione predefinita le nuove voci BO",
        "nl": "Nieuwe BO-items standaard vergrendelen",
        "pl": "Domyślnie blokuj nowe wpisy BO",
        "lb": "Nei BO-Entréeën standardméisseg spären"
    },
    "Lock new BO media by default": {
        "fr": "Verrouiller par défaut les nouveaux médias BO",
        "de": "Neue BO-Medien standardmäßig sperren",
        "es": "Bloquear por defecto los nuevos medios BO",
        "it": "Blocca per impostazione predefinita i nuovi media BO",
        "nl": "Nieuwe BO-media standaard vergrendelen",
        "pl": "Domyślnie blokuj nowe media BO",
        "lb": "Nei BO-Medien standardméisseg spären"
    },
    "Lock new BO offers by default": {
        "fr": "Verrouiller par défaut les nouvelles offres BO",
        "de": "Neue BO-Angebote standardmäßig sperren",
        "es": "Bloquear por defecto las nuevas ofertas BO",
        "it": "Blocca per impostazione predefinita le nuove offerte BO",
        "nl": "Nieuwe BO-aanbiedingen standaard vergrendelen",
        "pl": "Domyślnie blokuj nowe oferty BO",
        "lb": "Nei BO-Offeren standardméisseg spären"
    },
    "Manual catalogue curation": {
        "fr": "Curation manuelle du catalogue",
        "de": "Manuelle Katalogpflege",
        "es": "Curación manual del catálogo",
        "it": "Curazione manuale del catalogo",
        "nl": "Handmatige catalogusbeheer",
        "pl": "Ręczna kuracja katalogu",
        "lb": "Manuell Katalog-Kuratioun"
    },
    "Manual dictionary curation": {
        "fr": "Curation manuelle du dictionnaire",
        "de": "Manuelle Wörterbuchpflege",
        "es": "Curación manual del diccionario",
        "it": "Curazione manuale del dizionario",
        "nl": "Handmatig woordenboekbeheer",
        "pl": "Ręczna kuracja słownika",
        "lb": "Manuell Dictionnaire-Kuratioun"
    },
    "Missing catalogue definition": {
        "fr": "Définition absente du catalogue",
        "de": "Fehlende Katalogdefinition",
        "es": "Definición ausente del catálogo",
        "it": "Definizione mancante nel catalogo",
        "nl": "Ontbrekende catalogusdefinitie",
        "pl": "Brakująca definicja katalogu",
        "lb": "Feelend Katalog-Definitioun"
    },
    "Non-protected definitions": {
        "fr": "Définitions non protégées",
        "de": "Nicht geschützte Definitionen",
        "es": "Definiciones no protegidas",
        "it": "Definizioni non protette",
        "nl": "Niet-beschermde definities",
        "pl": "Niechronione definicje",
        "lb": "Net geschützt Definitiounen"
    },
    "Non-protected groups": {
        "fr": "Groupes non protégés",
        "de": "Nicht geschützte Gruppen",
        "es": "Grupos no protegidos",
        "it": "Gruppi non protetti",
        "nl": "Niet-beschermde groepen",
        "pl": "Niechronione grupy",
        "lb": "Net geschützt Gruppen"
    },
    "Offer feature values": {
        "fr": "Valeurs de caractéristiques d'offre",
        "de": "Angebots-Feature-Werte",
        "es": "Valores de características de oferta",
        "it": "Valori caratteristiche offerta",
        "nl": "Kenmerkwaarden van aanbiedingen",
        "pl": "Wartości cech ofert",
        "lb": "Offer-Feature-Wäerter"
    },
    "Preserve existing dictionary labels during CRM offer import": {
        "fr": "Conserver les libellés existants du dictionnaire lors de l'import d'offres CRM",
        "de": "Bestehende Wörterbuchlabels beim CRM-Angebotsimport beibehalten",
        "es": "Conservar etiquetas existentes del diccionario durante la importación de ofertas CRM",
        "it": "Conserva le etichette esistenti del dizionario durante l'import offerte CRM",
        "nl": "Bestaande woordenboeklabels behouden tijdens CRM-aanbiedingsimport",
        "pl": "Zachowaj istniejące etykiety słownika podczas importu ofert CRM",
        "lb": "Bestehend Dictionnaire-Labelen beim CRM-Offer-Import behalen"
    },
    "Preserve existing entry labels on CSV update": {
        "fr": "Conserver les libellés existants lors de la mise à jour CSV",
        "de": "Bestehende Eintragslabels bei CSV-Aktualisierung beibehalten",
        "es": "Conservar etiquetas existentes al actualizar CSV",
        "it": "Conserva le etichette esistenti durante l'aggiornamento CSV",
        "nl": "Bestaande itemlabels behouden bij CSV-update",
        "pl": "Zachowaj istniejące etykiety wpisów przy aktualizacji CSV",
        "lb": "Bestehend Entrée-Labelen bei CSV-Update behalen"
    },
    "Protected catalogue row strategy": {
        "fr": "Stratégie de ligne catalogue protégée",
        "de": "Geschützte Katalogzeilen-Strategie",
        "es": "Estrategia de fila de catálogo protegida",
        "it": "Strategia riga catalogo protetta",
        "nl": "Strategie voor beschermde catalogusrijen",
        "pl": "Strategia chronionego wiersza katalogu",
        "lb": "Geschützt Katalog-Zeile-Strategie"
    },
    "Reserved for a future dictionary protection model. Currently has no effect.": {
        "fr": "Réservé à un futur modèle de protection du dictionnaire. Sans effet pour l'instant.",
        "de": "Für ein zukünftiges Wörterbuchschutzmodell reserviert. Derzeit ohne Wirkung.",
        "es": "Reservado para un futuro modelo de protección del diccionario. Sin efecto por ahora.",
        "it": "Riservato a un futuro modello di protezione del dizionario. Attualmente senza effetto.",
        "nl": "Gereserveerd voor een toekomstig woordenboekbeschermingsmodel. Momenteel zonder effect.",
        "pl": "Zarezerwowane dla przyszłego modelu ochrony słownika. Obecnie bez efektu.",
        "lb": "Reservéiert fir e zukünftegt Dictionnaire-Schutzmodell. Aktuell ouni Effekt."
    },
    "Skip item and log a warning": {
        "fr": "Ignorer l'élément et journaliser un avertissement",
        "de": "Element überspringen und Warnung protokollieren",
        "es": "Omitir elemento y registrar una advertencia",
        "it": "Ignora elemento e registra un avviso",
        "nl": "Item overslaan en waarschuwing loggen",
        "pl": "Pomiń element i zapisz ostrzeżenie",
        "lb": "Element iwwersprangen an Warnung loggen"
    },
    "Sync translated definition labels from offer imports": {
        "fr": "Synchroniser les libellés traduits des définitions depuis les imports d'offres",
        "de": "Übersetzte Definitionslabels aus Angebotsimporten synchronisieren",
        "es": "Sincronizar etiquetas traducidas de definiciones desde importaciones de ofertas",
        "it": "Sincronizza etichette tradotte delle definizioni dagli import offerte",
        "nl": "Vertaalde definitielabels synchroniseren vanuit aanbiedingsimporten",
        "pl": "Synchronizuj przetłumaczone etykiety definicji z importów ofert",
        "lb": "Iwwersat Definitiouns-Labelen aus Offer-Importen synchroniséieren"
    },
    "The selected default feature group does not exist.": {
        "fr": "Le groupe de caractéristiques par défaut sélectionné n'existe pas.",
        "de": "Die ausgewählte Standard-Feature-Gruppe existiert nicht.",
        "es": "El grupo de características predeterminado seleccionado no existe.",
        "it": "Il gruppo caratteristiche predefinito selezionato non esiste.",
        "nl": "De geselecteerde standaard kenmerkengroep bestaat niet.",
        "pl": "Wybrana domyślna grupa cech nie istnieje.",
        "lb": "Déi gewielt Standard-Feature-Grupp existéiert net."
    },
    "Unpublish": {
        "fr": "Dépublier",
        "de": "Veröffentlichung aufheben",
        "es": "Despublicar",
        "it": "Rimuovi dalla pubblicazione",
        "nl": "Depubliceren",
        "pl": "Cofnij publikację",
        "lb": "Depublizéieren"
    },
    "Used by post-import synchronization when an offer disappears from the CRM XML snapshot.": {
        "fr": "Utilisé par la synchronisation post-import lorsqu'une offre disparaît du snapshot XML CRM.",
        "de": "Wird bei der Post-Import-Synchronisation verwendet, wenn ein Angebot aus dem CRM-XML-Snapshot verschwindet.",
        "es": "Usado por la sincronización post-importación cuando una oferta desaparece del snapshot XML CRM.",
        "it": "Usato dalla sincronizzazione post-import quando un'offerta scompare dallo snapshot XML CRM.",
        "nl": "Gebruikt door post-importsynchronisatie wanneer een aanbieding uit de CRM-XML-snapshot verdwijnt.",
        "pl": "Używane przez synchronizację po imporcie, gdy oferta znika ze snapshotu XML CRM.",
        "lb": "Gëtt bei Post-Import-Synchronisatioun benotzt wann eng Offer aus dem CRM-XML-Snapshot verschwënnt."
    },
    "Used when a CSV row, CRM element or offer import creates a feature definition without a group code. Falls back to @group when unset.": {
        "fr": "Utilisé lorsqu'une ligne CSV, un élément CRM ou un import d'offre crée une définition sans code de groupe. Retombe sur @group si non renseigné.",
        "de": "Wird verwendet, wenn eine CSV-Zeile, ein CRM-Element oder ein Angebotsimport eine Feature-Definition ohne Gruppencode erstellt. Fällt auf @group zurück, wenn nicht gesetzt.",
        "es": "Se usa cuando una fila CSV, elemento CRM o importación de oferta crea una definición sin código de grupo. Recurre a @group si no está definido.",
        "it": "Usato quando una riga CSV, elemento CRM o import offerta crea una definizione senza codice gruppo. Ricade su @group se non impostato.",
        "nl": "Gebruikt wanneer een CSV-rij, CRM-element of aanbiedingsimport een definitie zonder groepscode aanmaakt. Valt terug op @group indien niet ingesteld.",
        "pl": "Używane, gdy wiersz CSV, element CRM lub import oferty tworzy definicję bez kodu grupy. Wraca do @group, gdy nie ustawiono.",
        "lb": "Gëtt benotzt wann eng CSV-Zeile, CRM-Element oder Offer-Import eng Definitioun ouni Gruppencode erstellt. Fält op @group zréck wann net gesat."
    },
    "When checked, CSV imports only update weight for existing entries and keep their current labels.": {
        "fr": "Si coché, les imports CSV ne mettent à jour que le poids des entrées existantes et conservent leurs libellés.",
        "de": "Wenn aktiviert, aktualisieren CSV-Importe nur das Gewicht bestehender Einträge und behalten deren Labels bei.",
        "es": "Si está marcado, las importaciones CSV solo actualizan el peso de entradas existentes y conservan sus etiquetas.",
        "it": "Se selezionato, gli import CSV aggiornano solo il peso delle voci esistenti e mantengono le etichette attuali.",
        "nl": "Indien aangevinkt, werken CSV-importen alleen het gewicht van bestaande items bij en behouden de huidige labels.",
        "pl": "Po zaznaczeniu importy CSV aktualizują tylko wagę istniejących wpisów i zachowują ich etykiety.",
        "lb": "Wann aktiv, aktualiséieren CSV-Importen nëmmen d'Gewiicht vun bestehenden Entréeën a behalen hir Labelen."
    },
    "When checked, media created in the back office start with field_internal_lock enabled.": {
        "fr": "Si coché, les médias créés en back-office démarrent avec field_internal_lock activé.",
        "de": "Wenn aktiviert, starten im Backoffice erstellte Medien mit aktiviertem field_internal_lock.",
        "es": "Si está marcado, los medios creados en back office empiezan con field_internal_lock activado.",
        "it": "Se selezionato, i media creati nel back office partono con field_internal_lock abilitato.",
        "nl": "Indien aangevinkt, starten media aangemaakt in de backoffice met field_internal_lock ingeschakeld.",
        "pl": "Po zaznaczeniu media utworzone w back office mają włączony field_internal_lock.",
        "lb": "Wann aktiv, starten am Backoffice erstellt Medien mat aktivéiertem field_internal_lock."
    },
    "When checked, offer imports keep existing dictionary entry labels instead of overwriting them from XML-derived values.": {
        "fr": "Si coché, les imports d'offres conservent les libellés existants du dictionnaire au lieu de les écraser depuis le XML.",
        "de": "Wenn aktiviert, behalten Angebotsimporte bestehende Wörterbuchlabels statt sie aus XML-Werten zu überschreiben.",
        "es": "Si está marcado, las importaciones de ofertas conservan las etiquetas existentes del diccionario en lugar de sobrescribirlas desde el XML.",
        "it": "Se selezionato, gli import offerte mantengono le etichette esistenti del dizionario invece di sovrascriverle dai valori XML.",
        "nl": "Indien aangevinkt, behouden aanbiedingsimporten bestaande woordenboeklabels in plaats van ze te overschrijven vanuit XML.",
        "pl": "Po zaznaczeniu importy ofert zachowują istniejące etykiety słownika zamiast nadpisywać je wartościami z XML.",
        "lb": "Wann aktiv, behalen Offer-Importen bestehend Dictionnaire-Labelen amplaz se aus XML-Wäerter ze iwwerschreiwen."
    },
    "When checked, offer imports may update translated feature definition labels, including for catalogue-protected definitions.": {
        "fr": "Si coché, les imports d'offres peuvent mettre à jour les libellés traduits des définitions, y compris pour les définitions protégées du catalogue.",
        "de": "Wenn aktiviert, können Angebotsimporte übersetzte Feature-Definitionslabels aktualisieren, auch für kataloggeschützte Definitionen.",
        "es": "Si está marcado, las importaciones de ofertas pueden actualizar etiquetas traducidas de definiciones, incluso las protegidas del catálogo.",
        "it": "Se selezionato, gli import offerte possono aggiornare le etichette tradotte delle definizioni, incluse quelle protette del catalogo.",
        "nl": "Indien aangevinkt, kunnen aanbiedingsimporten vertaalde definitielabels bijwerken, ook voor catalogusbeschermde definities.",
        "pl": "Po zaznaczeniu importy ofert mogą aktualizować przetłumaczone etykiety definicji, także chronionych katalogiem.",
        "lb": "Wann aktiv, kënnen Offer-Importen iwwersat Feature-Definitiouns-Labelen aktualiséieren, och fir katalog-geschützt Definitiounen."
    },
    "When checked, offers created in the back office start with field_internal_lock enabled.": {
        "fr": "Si coché, les offres créées en back-office démarrent avec field_internal_lock activé.",
        "de": "Wenn aktiviert, starten im Backoffice erstellte Angebote mit aktiviertem field_internal_lock.",
        "es": "Si está marcado, las ofertas creadas en back office empiezan con field_internal_lock activado.",
        "it": "Se selezionato, le offerte create nel back office partono con field_internal_lock abilitato.",
        "nl": "Indien aangevinkt, starten aanbiedingen aangemaakt in de backoffice met field_internal_lock ingeschakeld.",
        "pl": "Po zaznaczeniu oferty utworzone w back office mają włączony field_internal_lock.",
        "lb": "Wann aktiv, starten am Backoffice erstellt Offeren mat aktivéiertem field_internal_lock."
    },
    "When enabled, domain forms display the effective global CRM lock strategy next to inherit options.": {
        "fr": "Lorsque cette option est activée, les formulaires domaine affichent la stratégie CRM globale effective à côté des options Hériter.",
        "de": "Wenn aktiviert, zeigen Domänenformulare die wirksame globale CRM-Sperrstrategie neben Erben-Optionen an.",
        "es": "Si está activado, los formularios de dominio muestran la estrategia de bloqueo CRM global efectiva junto a las opciones Heredar.",
        "it": "Se abilitato, i moduli di dominio mostrano la strategia di blocco CRM globale effettiva accanto alle opzioni Eredita.",
        "nl": "Indien ingeschakeld, tonen domeinformulieren de effectieve globale CRM-vergrendelingsstrategie naast Overnemen-opties.",
        "pl": "Po włączeniu formularze domenowe wyświetlają skuteczną globalną strategię blokady CRM obok opcji Dziedzicz.",
        "lb": "Wann aktiv, weisen Domain-Formulare déi effektiv global CRM-Spärstrategie nieft Iwwerhuelen-Optiounen."
    },
    "When unchecked, existing agents keep their email and phone during CRM imports.": {
        "fr": "Si décoché, les agents existants conservent leur e-mail et téléphone lors des imports CRM.",
        "de": "Wenn deaktiviert, behalten bestehende Agenten ihre E-Mail und Telefonnummer bei CRM-Importen.",
        "es": "Si no está marcado, los agentes existentes conservan su correo y teléfono durante importaciones CRM.",
        "it": "Se deselezionato, gli agenti esistenti mantengono email e telefono durante gli import CRM.",
        "nl": "Indien uitgevinkt, behouden bestaande agenten hun e-mail en telefoon tijdens CRM-importen.",
        "pl": "Po odznaczeniu istniejący agenci zachowują e-mail i telefon podczas importów CRM.",
        "lb": "Wann desaktivéiert, behalen bestehend Agenten hir E-Mail an Telefon bei CRM-Importen."
    },
    "When unchecked, existing definitions keep their icon and search filter exposure during CRM imports.": {
        "fr": "Si décoché, les définitions existantes conservent leur icône et exposition filtre lors des imports CRM.",
        "de": "Wenn deaktiviert, behalten bestehende Definitionen ihr Icon und die Filteranzeige bei CRM-Importen.",
        "es": "Si no está marcado, las definiciones existentes conservan su icono y exposición de filtro durante importaciones CRM.",
        "it": "Se deselezionato, le definizioni esistenti mantengono icona ed esposizione filtro durante gli import CRM.",
        "nl": "Indien uitgevinkt, behouden bestaande definities hun pictogram en filterweergave tijdens CRM-importen.",
        "pl": "Po odznaczeniu istniejące definicje zachowują ikonę i ekspozycję filtra podczas importów CRM.",
        "lb": "Wann desaktivéiert, behalen bestehend Definitiounen hiert Icon an Filter-Uweis bei CRM-Importen."
    },
    "When unchecked, existing media keeps its image alt text and virtual tour link title during CRM imports.": {
        "fr": "Si décoché, les médias existants conservent le texte alternatif et le titre du lien visite virtuelle lors des imports CRM.",
        "de": "Wenn deaktiviert, behalten bestehende Medien ihren Bild-Alt-Text und den Linktitel der virtuellen Tour bei CRM-Importen.",
        "es": "Si no está marcado, los medios existentes conservan el texto alternativo y el título del enlace de visita virtual durante importaciones CRM.",
        "it": "Se deselezionato, i media esistenti mantengono il testo alternativo e il titolo del link tour virtuale durante gli import CRM.",
        "nl": "Indien uitgevinkt, behouden bestaande media hun alt-tekst en titel van de virtuele tourlink tijdens CRM-importen.",
        "pl": "Po odznaczeniu istniejące media zachowują tekst alternatywny obrazu i tytuł linku wirtualnego spaceru podczas importów CRM.",
        "lb": "Wann desaktivéiert, behalen bestehend Medien hiren Bild-Alt-Text an de Link-Titel vun der virtueller Tour bei CRM-Importen."
    },
    "When unchecked, existing offers keep their reference mode and manual reference during CRM imports.": {
        "fr": "Si décoché, les offres existantes conservent leur mode de référence et référence manuelle lors des imports CRM.",
        "de": "Wenn deaktiviert, behalten bestehende Angebote ihren Referenzmodus und die manuelle Referenz bei CRM-Importen.",
        "es": "Si no está marcado, las ofertas existentes conservan su modo de referencia y referencia manual durante importaciones CRM.",
        "it": "Se deselezionato, le offerte esistenti mantengono modalità di riferimento e riferimento manuale durante gli import CRM.",
        "nl": "Indien uitgevinkt, behouden bestaande aanbiedingen hun referentiemodus en handmatige referentie tijdens CRM-importen.",
        "pl": "Po odznaczeniu istniejące oferty zachowują tryb referencji i referencję ręczną podczas importów CRM.",
        "lb": "Wann desaktivéiert, behalen bestehend Offeren hire Referenzmodus an manuell Referenz bei CRM-Importen."
    }
}
