ps_demo.settings:
  type: config_object
  label: 'PS Demo settings'
  mapping:
    front_page:
      type: string
      label: 'Front page internal path'
    homepage_uuid:
      type: uuid
      label: 'Homepage node UUID (export reference)'
    front_paths:
      type: mapping
      label: 'Homepage URL aliases per language'
      mapping:
        en:
          type: string
          label: 'English alias'
        fr:
          type: string
          label: 'French alias'

ps_demo.homepage:
  type: config_object
  label: 'PS Demo homepage metadata'
  mapping:
    node:
      type: mapping
      label: 'Homepage node metadata'
      mapping:
        titles:
          type: mapping
          label: Titles
          mapping:
            en:
              type: label
              label: 'English title'
            fr:
              type: label
              label: 'French title'
        path:
          type: mapping
          label: Paths
          mapping:
            en:
              type: string
              label: 'English alias'
            fr:
              type: string
              label: 'French alias'
