((Drupal, once) => {
  Drupal.ui_suite_bnppre_carousel = Drupal.ui_suite_bnppre_carousel || {};

  /**
   * Ensure modal is mounted at body level to avoid stacking-context issues.
   *
   * @param {HTMLElement} modal
   *   Modal element.
   */
  function ensureModalInBody(modal) {
    if (modal.parentElement !== document.body) {
      document.body.appendChild(modal);
    }
  }

  function cleanupOrphanBackdrops() {
    if (document.querySelector('.modal.show')) {
      return;
    }

    document.querySelectorAll('.modal-backdrop').forEach((backdrop) => {
      backdrop.remove();
    });

    document.body.classList.remove('modal-open');
    document.body.style.removeProperty('padding-right');
  }

  function normalizeModalStacking(modal) {
    const modalZIndex = 1100;
    modal.style.zIndex = String(modalZIndex);

    const backdrops = Array.from(document.querySelectorAll('.modal-backdrop'));
    if (!backdrops.length) {
      return;
    }

    // Keep only the last backdrop generated by Bootstrap.
    backdrops.slice(0, -1).forEach((backdrop) => backdrop.remove());
    const activeBackdrop = backdrops.at(-1);
    if (activeBackdrop) {
      activeBackdrop.style.zIndex = String(modalZIndex - 10);
    }
  }

  function getActiveSlideIndex(carousel) {
    const slides = Array.from(carousel.querySelectorAll('.carousel-item'));
    const index = slides.findIndex((slide) => slide.classList.contains('active'));
    return index >= 0 ? index : 0;
  }

  function moveSourceCarouselTo(carousel, index) {
    const bootstrapApi = window.bootstrap;
    if (!bootstrapApi || !bootstrapApi.Carousel) {
      return;
    }

    const instance = bootstrapApi.Carousel.getOrCreateInstance(carousel, {
      interval: false,
      ride: false,
      wrap: true,
      touch: false,
    });
    instance.to(index);
  }

  function getToolbarGroups(carousel) {
    const buttons = Array.from(
      carousel.querySelectorAll('[data-carousel-toolbar-item]'),
    );
    const slides = Array.from(carousel.querySelectorAll('.carousel-item'));

    return buttons.map((button, index) => {
      const start = Number.parseInt(button.dataset.slideIndex || '0', 10);
      const next = buttons[index + 1];
      const end = next
        ? Number.parseInt(next.dataset.slideIndex || String(start), 10) - 1
        : slides.length - 1;

      return {
        button,
        start,
        end,
        openMode: button.dataset.openMode || 'media',
        externalItems: parseExternalItems(button.dataset.externalItems),
      };
    });
  }

  /**
   * Find the toolbar group that owns a slide index.
   *
   * @param {Array<object>} groups
   *   Group descriptors.
   * @param {number} index
   *   Slide index.
   *
   * @returns {object|null}
   *   Matching group or null.
   */
  function getGroupForSlideIndex(groups, index) {
    return groups.find((group) => index >= group.start && index <= group.end) || null;
  }

  function syncModalThumbs(modalCarousel, thumbsContainer) {
    const slides = Array.from(modalCarousel.querySelectorAll('.carousel-item'));
    const thumbs = Array.from(
      thumbsContainer.querySelectorAll('[data-carousel-modal-thumb]'),
    );
    const activeIndex = slides.findIndex((slide) =>
      slide.classList.contains('active'),
    );

    thumbs.forEach((thumb, index) => {
      const isActive = index === activeIndex;
      thumb.classList.toggle('is-active', isActive);
      thumb.setAttribute('aria-current', isActive ? 'true' : 'false');
    });
  }

  function parseExternalItems(value) {
    if (!value) {
      return [];
    }

    try {
      const parsed = JSON.parse(value);
      if (!Array.isArray(parsed)) {
        return [];
      }

      return parsed
        .map((item) => ({
          url: typeof item.url === 'string' ? item.url.trim() : '',
          title: typeof item.title === 'string' ? item.title.trim() : '',
        }))
        .filter((item) => item.url !== '' && isSafeExternalUrl(item.url));
    }
    catch {
      return [];
    }
  }

  function isSafeExternalUrl(url) {
    try {
      const parsedUrl = new URL(url, window.location.origin);
      return ['http:', 'https:'].includes(parsedUrl.protocol);
    }
    catch {
      return false;
    }
  }

  function getSlideTitle(sourceSlide, fallbackTitle) {
    const sourceImage = sourceSlide.querySelector('img[alt]');
    const title = sourceImage?.getAttribute('alt')?.trim();
    return title || fallbackTitle || Drupal.t('Media slide');
  }

  function buildModalSlidesManifest(carousel) {
    const groups = getToolbarGroups(carousel);
    const sourceSlides = Array.from(carousel.querySelectorAll('.carousel-item'));

    return sourceSlides.map((sourceSlide, index) => {
      const group = getGroupForSlideIndex(groups, index);
      if (group && group.openMode === 'external') {
        const externalIndex = index - group.start;
        const externalItem = group.externalItems[externalIndex];
        if (externalItem) {
          return {
            type: 'external',
            title: externalItem.title || Drupal.t('External media @number', {
              '@number': String(externalIndex + 1),
            }),
            url: externalItem.url,
          };
        }
      }

      // Check if this is a video slide.
      const mediaType = sourceSlide.getAttribute('data-media-type');
      const mediaBundle = sourceSlide.getAttribute('data-media-bundle');
      const videoUrl = sourceSlide.getAttribute('data-video-url');

      if (mediaType === 'video' && videoUrl) {
        return {
          type: 'video',
          mediaBundle,
          title: getSlideTitle(sourceSlide, group?.button.textContent?.trim()),
          videoUrl,
          sourceSlide,
        };
      }

      return {
        type: 'media',
        title: getSlideTitle(sourceSlide, group?.button.textContent?.trim()),
        sourceSlide,
      };
    });
  }

  function buildMediaModalSlide(item, index) {
    const modalSlide = document.createElement('div');
    modalSlide.className = `carousel-item${index === 0 ? ' active' : ''}`;

    if (item.type === 'external') {
      modalSlide.classList.add('ps-carousel-media-modal__carousel-slide--external');

      const frameWrap = document.createElement('div');
      frameWrap.className = 'ps-carousel-media-modal__frame-wrap';

      const frame = document.createElement('iframe');
      frame.className = 'ps-carousel-media-modal__frame';
      frame.src = item.url;
      frame.title = item.title;
      frame.loading = 'lazy';
      frame.setAttribute('allowfullscreen', '');
      frame.setAttribute(
        'sandbox',
        'allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-presentation',
      );

      const fallbackLink = document.createElement('a');
      fallbackLink.href = item.url;
      fallbackLink.target = '_blank';
      fallbackLink.rel = 'noopener noreferrer';
      fallbackLink.className = 'ps-carousel-media-modal__fallback-link';
      fallbackLink.textContent = item.title || Drupal.t('Open link');

      frameWrap.appendChild(frame);
      frameWrap.appendChild(fallbackLink);
      modalSlide.appendChild(frameWrap);
      return modalSlide;
    }

    // Handle video media.
    if (item.type === 'video' && item.videoUrl) {
      modalSlide.classList.add('ps-carousel-media-modal__carousel-slide--video');

      const mediaContainer = document.createElement('div');
      mediaContainer.className = 'ps-carousel-media-modal__video-container';

      // For local videos: use HTML5 video element.
      if (item.mediaBundle === 'videos') {
        const video = document.createElement('video');
        video.className = 'ps-carousel-media-modal__video';
        video.controls = true;
        video.title = item.title;
        video.setAttribute('controlsList', 'nodownload');
        video.style.width = '100%';
        video.style.maxHeight = '80vh';
        video.style.objectFit = 'contain';

        const source = document.createElement('source');
        source.src = item.videoUrl;
        source.type = 'video/mp4';

        video.appendChild(source);
        const fallbackText = document.createTextNode(Drupal.t('Your browser does not support the video tag.'));
        video.appendChild(fallbackText);

        mediaContainer.appendChild(video);
      }
      // For remote videos (oEmbed): use iframe.
      else if (item.mediaBundle === 'remote_video') {
        const frameWrap = document.createElement('div');
        frameWrap.className = 'ps-carousel-media-modal__frame-wrap';

        const frame = document.createElement('iframe');
        frame.className = 'ps-carousel-media-modal__frame ps-carousel-media-modal__video-iframe';
        frame.src = item.videoUrl;
        frame.title = item.title;
        frame.loading = 'lazy';
        frame.setAttribute('allowfullscreen', '');
        frame.setAttribute(
          'sandbox',
          'allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox allow-presentation',
        );

        frameWrap.appendChild(frame);
        mediaContainer.appendChild(frameWrap);
      }

      modalSlide.appendChild(mediaContainer);
      return modalSlide;
    }

    const sourceImage = item.sourceSlide.querySelector('img');
    if (sourceImage) {
      const modalImage = sourceImage.cloneNode(false);
      modalImage.classList.add('ps-carousel-media-modal__image');
      modalImage.removeAttribute('loading');
      modalSlide.appendChild(modalImage);
      return modalSlide;
    }

    const sourceSlide = item.sourceSlide.cloneNode(true);
    sourceSlide.classList.remove(
      'carousel-item',
      'active',
      'carousel-item-next',
      'carousel-item-prev',
      'carousel-item-start',
      'carousel-item-end',
    );
    sourceSlide.classList.add('ps-carousel-media-modal__fallback-content');
    modalSlide.appendChild(sourceSlide);
    return modalSlide;
  }

  function buildMediaModalThumb(item, modalCarouselId, index) {
    const thumb = document.createElement('button');
    thumb.type = 'button';
    thumb.className = `ps-carousel-media-modal__thumb${index === 0 ? ' is-active' : ''}`;
    thumb.setAttribute('data-carousel-modal-thumb', '');
    thumb.setAttribute('data-bs-target', `#${modalCarouselId}`);
    thumb.setAttribute('data-bs-slide-to', String(index));
    thumb.setAttribute(
      'aria-label',
      Drupal.t('Go to slide @number', {
        '@number': String(index + 1),
      }),
    );
    thumb.setAttribute('aria-current', index === 0 ? 'true' : 'false');

    if (item.type === 'media') {
      const sourceImage = item.sourceSlide.querySelector('img');
      if (sourceImage) {
        const thumbImage = sourceImage.cloneNode(false);
        thumbImage.removeAttribute('loading');
        thumbImage.classList.add('ps-carousel-media-modal__thumb-image');
        thumb.appendChild(thumbImage);
        return thumb;
      }
    }

    const thumbLabel = document.createElement('span');
    thumbLabel.className = 'ps-carousel-media-modal__thumb-label';
    thumbLabel.textContent = item.title;
    thumb.appendChild(thumbLabel);
    return thumb;
  }

  function populateModalCarousel(carousel, modalCarousel, thumbsContainer) {
    const modalSlides = modalCarousel.querySelector('[data-carousel-modal-slides]');
    if (!modalSlides) {
      return;
    }

    const manifest = buildModalSlidesManifest(carousel);
    modalSlides.innerHTML = '';
    thumbsContainer.innerHTML = '';

    manifest.forEach((item, index) => {
      modalSlides.appendChild(buildMediaModalSlide(item, index));
      thumbsContainer.appendChild(
        buildMediaModalThumb(item, modalCarousel.id, index),
      );
    });

    modalCarousel.addEventListener('slid.bs.carousel', () => {
      syncModalThumbs(modalCarousel, thumbsContainer);
      moveSourceCarouselTo(carousel, getActiveSlideIndex(modalCarousel));
    });
  }

  function openMediaModal(carousel, requestedIndex, focusTarget) {
    const bootstrapApi = window.bootstrap;
    if (!bootstrapApi || !bootstrapApi.Modal || !bootstrapApi.Carousel) {
      return;
    }

    const modalTarget = carousel.dataset.carouselModalTarget;
    if (!modalTarget) {
      return;
    }

    const modal = document.querySelector(modalTarget);
    if (!modal) {
      return;
    }

    ensureModalInBody(modal);

    const modalCarouselId = carousel.dataset.carouselModalCarouselId;
    const modalCarousel = modalCarouselId
      ? modal.querySelector(`#${modalCarouselId}`)
      : null;
    const thumbsContainer = modal.querySelector('[data-carousel-modal-thumbs]');
    if (!modalCarousel || !thumbsContainer) {
      return;
    }

    if (modal.dataset.carouselModalBuilt !== 'true') {
      populateModalCarousel(carousel, modalCarousel, thumbsContainer);
      modal.dataset.carouselModalBuilt = 'true';
    }

    const modalCarouselInstance = bootstrapApi.Carousel.getOrCreateInstance(
      modalCarousel,
      {
        interval: false,
        ride: false,
        wrap: true,
      },
    );
    modalCarouselInstance.to(requestedIndex);
    syncModalThumbs(modalCarousel, thumbsContainer);

    const modalInstance = bootstrapApi.Modal.getOrCreateInstance(modal);
    cleanupOrphanBackdrops();
    modal.addEventListener(
      'shown.bs.modal',
      () => {
        normalizeModalStacking(modal);
        const closeButton = modal.querySelector('.btn-close');
        if (closeButton) {
          closeButton.focus();
        }
      },
      { once: true },
    );
    modal.addEventListener(
      'hidden.bs.modal',
      () => {
        cleanupOrphanBackdrops();
        if (focusTarget) {
          focusTarget.focus();
        }
      },
      { once: true },
    );
    modalInstance.show();
  }

  function syncToolbarState(carousel) {
    const buttons = Array.from(
      carousel.querySelectorAll('[data-carousel-toolbar-item]'),
    );
    if (!buttons.length) {
      return;
    }

    const slides = Array.from(carousel.querySelectorAll('.carousel-item'));
    const activeIndex = slides.findIndex((slide) =>
      slide.classList.contains('active'),
    );

    if (activeIndex < 0) {
      return;
    }

    buttons.forEach((button, index) => {
      const start = Number.parseInt(button.dataset.slideIndex || '0', 10);
      const next = buttons[index + 1];
      const end = next
        ? Number.parseInt(next.dataset.slideIndex || String(start), 10) - 1
        : slides.length - 1;
      const isActive = activeIndex >= start && activeIndex <= end;

      button.classList.toggle('is-active', isActive);
      button.setAttribute('aria-selected', isActive ? 'true' : 'false');
      button.tabIndex = isActive ? 0 : -1;
    });
  }

  /**
   * Set active class on the first item.
   *
   * @type {Drupal~behavior}
   *
   * @prop {Drupal~behaviorAttach} attach
   *   Attaches the behaviors for the active class.
   */
  Drupal.behaviors.ui_suite_bnppre_carousel = {
    attach(context) {
      once('carousel-active', '.carousel', context).forEach((carousel) => {
        const items = carousel.querySelectorAll(
          '.carousel-inner .carousel-item',
        );
        if (items.length === 0) {
          return;
        }

        items.item(0).classList.add('active');
      });

      once('carousel-toolbar-state', '.carousel[data-carousel-toolbar="true"]', context)
        .forEach((carousel) => {
          syncToolbarState(carousel);
          carousel.addEventListener('slid.bs.carousel', () => {
            syncToolbarState(carousel);
          });
        });

      once(
        'carousel-toolbar-modal',
        '.carousel[data-carousel-toolbar="true"][data-carousel-modal="true"]',
        context,
      ).forEach((carousel) => {
        const buttons = Array.from(
          carousel.querySelectorAll('[data-carousel-toolbar-item]'),
        );
        buttons.forEach((button) => {
          button.addEventListener('click', (event) => {
            event.preventDefault();

            const bootstrapApi = window.bootstrap;
            if (bootstrapApi && bootstrapApi.Carousel) {
              const targetIndex = Number.parseInt(
                button.dataset.slideIndex || '0',
                10,
              );
              const sourceCarousel = bootstrapApi.Carousel.getOrCreateInstance(
                carousel,
                {
                  interval: false,
                  ride: false,
                },
              );
              sourceCarousel.to(Number.isNaN(targetIndex) ? 0 : targetIndex);

              openMediaModal(
                carousel,
                Number.isNaN(targetIndex) ? 0 : targetIndex,
                button,
              );
              return;
            }
          });
        });
      });
    },
  };
})(Drupal, once);
